// lib/offres/basics.ts
import type { OffreComplet } from "./type";

const workflowsCommuns = {
  basiques: [
    {
      id: "wf-01",
      titre: "Workflow #01 — Sync entrante",
      description:
        "Création/Lead → Notif Slack → Google Sheets → Email bienvenue",
      categoriePrix: "basique" as const,
    },
    {
      id: "wf-02",
      titre: "Workflow #02 — Validation manuelle",
      description: "Entrée → validation humaine → actions conditionnelles",
      categoriePrix: "basique" as const,
    },
  ],
  standards: [
    {
      id: "wf-03",
      titre: "Workflow #03 — Logique conditionnelle",
      description: "Branchement selon valeur champ → actions différentes",
      categoriePrix: "standard" as const,
    },
    {
      id: "wf-04",
      titre: "Workflow #04 — Reporting automatique",
      description: "Aggrégation données → rapport PDF → Slack/Email",
      categoriePrix: "standard" as const,
    },
  ],
  pros: [
    {
      id: "wf-05",
      titre: "Workflow #05 — IA avancée",
      description: "Analyse IA → décision auto → actions contextuelles",
      categoriePrix: "pro" as const,
    },
    {
      id: "wf-06",
      titre: "Workflow #06 — Orchestration multi-étapes",
      description: "Chaîne complexe avec fallbacks et retry",
      categoriePrix: "pro" as const,
    },
  ],
};

export const basicsOffres: OffreComplet[] = [
  {
    id: 1,
    slug: "crm-automation",
    categorie: "basique",
    imageId: 1,
    titre: "Automatisation CRM",
    descriptionCourte:
      "HubSpot, Salesforce ou GHL — sync contacts, pipelines, notifications",
    descriptionLongue: `Votre CRM connecté automatiquement à vos emails, Slack, Google Sheets et outils de facturation. Les données circulent sans intervention manuelle.`,
    outils: [
      "Make",
      "n8n",
      "HubSpot",
      "Salesforce",
      "GHL",
      "Slack",
      "Google Sheets",
    ],
    secteurs: ["ventes", "marketing", "saas"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        description: "1 CRM + 2 outils connectés",
        features: [
          "Sync contacts",
          "Notifications Slack",
          "Google Sheets update",
        ],
        missingFeatures: ["Logique conditionnelle", "Reporting auto"],
        workflows: ["Sync CRM → Sheets", "Alertes Slack"],
        livrables: ["2 workflows", "Doc PDF"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 600,
        delaiJours: 5,
        description: "1 CRM + 5 outils",
        features: [
          "Multi-outils",
          "Logique conditionnelle",
          "Reporting basique",
        ],
        workflows: ["Sync CRM → Sheets", "Alertes Slack", "Logique conditions"],
        livrables: ["5 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1200,
        delaiJours: 7,
        description: "Multi-CRM + workflows complexes",
        features: [
          "Multi-CRM",
          "Workflows avancés",
          "Dashboard temps réel",
          "Support prioritaire",
        ],
        workflows: ["Tous workflows", "Orchestration avancée"],
        livrables: ["Tous workflows", "Doc + formation", "Support 30j"],
        supportJours: 30,
      },
    ],
    workflows: [
      ...workflowsCommuns.basiques,
      ...workflowsCommuns.standards,
      ...workflowsCommuns.pros,
    ],
  },
  {
    id: 2,
    slug: "email-automation",
    categorie: "basique",
    imageId: 2,
    titre: "Email Automation",
    descriptionCourte: "Séquences, relances, tri IA, réponses automatiques",
    descriptionLongue: `Vos emails partent seuls, au bon moment, au bon contact. Séquences de vente, relances intelligentes, tri de boîte mail par IA.`,
    outils: ["Make", "n8n", "Gmail API", "OpenAI", "HubSpot"],
    secteurs: ["marketing", "ventes", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 3,
        description: "1 séquence email",
        features: [
          "1 séquence (3 emails)",
          "Déclencheur formulaire/CRM",
          "Relance 1 niveau",
        ],
        missingFeatures: ["Tri IA", "Réponses auto IA"],
        workflows: ["Séquence bienvenue", "Relance simple"],
        livrables: ["2 JSONs", "Doc PDF"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 450,
        delaiJours: 5,
        description: "Séquences multi-étapes",
        features: [
          "3 séquences (5 emails)",
          "Logique conditionnelle",
          "Relances 3 niveaux",
          "Sync CRM",
          "Reporting hebdo",
        ],
        workflows: [
          "Séquences bienvenue",
          "Relances",
          "Conditionnelle",
          "Post-achat",
          "Reporting",
        ],
        livrables: ["5 JSONs", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 900,
        delaiJours: 7,
        description: "IA avancée",
        features: [
          "Tri IA boîte mail",
          "Réponses auto IA",
          "Détection intention",
          "Escalade mécontent",
          "A/B testing",
        ],
        workflows: ["Tous workflows basiques + IA"],
        livrables: ["8 JSONs", "Doc + formation", "Clé API OpenAI"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "email-01",
        titre: "Email #01 — Séquence bienvenue",
        description:
          "Formulaire → J0 bienvenue → J3 ressource → J7 appel action",
        categoriePrix: "basique",
      },
      {
        id: "email-02",
        titre: "Email #02 — Relance non-réponse",
        description:
          "X jours sans réponse → relance douce → valeur → fermeture",
        categoriePrix: "basique",
      },
      {
        id: "email-03",
        titre: "Email #03 — Conditionnelle",
        description: "Ouvert → séquence chaude / Non ouvert → objet différent",
        categoriePrix: "standard",
      },
      {
        id: "email-04",
        titre: "Email #04 — Post-achat",
        description:
          "Achat → J0 confirmation → J1 ressources → J3 check-in → J7 upsell",
        categoriePrix: "standard",
      },
      {
        id: "email-05",
        titre: "Email #05 — Reporting hebdo",
        description: "Stats emails → Google Sheets → Slack",
        categoriePrix: "standard",
      },
      {
        id: "email-06",
        titre: "Email #06 — Tri IA",
        description: "IA détecte intention → catégorise → route",
        categoriePrix: "pro",
      },
      {
        id: "email-07",
        titre: "Email #07 — Réponse auto IA",
        description: "IA lit → génère réponse contextuelle → envoie",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 3,
    slug: "lead-generation",
    categorie: "basique",
    imageId: 3,
    titre: "Lead Generation Automation",
    descriptionCourte: "Scraping · enrichissement · injection CRM · outreach",
    descriptionLongue: `Générez des leads en continu sans effort manuel. Scraping ciblé, enrichissement, injection CRM et outreach automatique.`,
    outils: ["n8n", "Make", "Apify", "HubSpot", "Salesforce"],
    secteurs: ["ventes", "marketing", "recrutement"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 4,
        description: "1 source scraping + injection",
        features: [
          "1 source scraping",
          "Enrichissement basique",
          "Injection CRM",
        ],
        workflows: ["Scraping → CSV → CRM"],
        livrables: ["2 workflows", "Doc PDF"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 700,
        delaiJours: 6,
        description: "Multi-sources + outreach",
        features: [
          "3 sources",
          "Enrichissement avancé",
          "Injection CRM",
          "Séquence outreach",
        ],
        workflows: ["Scraping multi-sources", "Enrichissement", "Outreach"],
        livrables: ["5 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1500,
        delaiJours: 10,
        description: "Pipeline complet + IA",
        features: [
          "Sources illimitées",
          "Scoring IA leads",
          "Dashboard temps réel",
          "Maintenance incluse",
        ],
        livrables: ["Pipeline complet", "Documentation", "Support 30j"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "lead-01",
        titre: "Lead #01 — Scraping simple",
        description: "Source cible → extraction → CSV",
        categoriePrix: "basique",
      },
      {
        id: "lead-02",
        titre: "Lead #02 — Enrichissement",
        description: "Email → recherche → données complètes",
        categoriePrix: "standard",
      },
      {
        id: "lead-03",
        titre: "Lead #03 — Outreach auto",
        description: "Lead → email séquence → suivi",
        categoriePrix: "standard",
      },
      {
        id: "lead-04",
        titre: "Lead #04 — Scoring IA",
        description: "Score leads → priorisation vente",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 4,
    slug: "api-webhook-integration",
    categorie: "basique",
    imageId: 4,
    titre: "API & Webhook Integration",
    descriptionCourte: "Connecter n'importe quelles apps via REST / webhooks",
    descriptionLongue: `Pas de connecteur natif ? On construit des intégrations sur mesure via API REST et webhooks. Toute app avec API peut être connectée.`,
    outils: ["n8n", "Make", "REST APIs", "Webhooks"],
    secteurs: ["tech", "saas", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 250,
        delaiJours: 3,
        description: "1 API connectée",
        features: ["1 endpoint entrant", "1 sortant", "Auth basique"],
        workflows: ["Webhook → traitement → sortie"],
        livrables: ["Workflow", "Doc API"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 500,
        delaiJours: 5,
        description: "Multi-API",
        features: ["3 APIs", "Auth avancée", "Gestion erreurs", "Logs"],
        workflows: ["Multi-API orchestration"],
        livrables: ["3 workflows", "Doc technique"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1000,
        delaiJours: 7,
        description: "API custom",
        features: [
          "API illimitées",
          "Rate limiting",
          "Webhook dashboard",
          "Monitoring",
        ],
        livrables: ["Plateforme intégration", "Documentation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "api-01",
        titre: "API #01 — Webhook entrant",
        description: "Reçoit data → transforme → envoie",
        categoriePrix: "basique",
      },
      {
        id: "api-02",
        titre: "API #02 — Orchestration",
        description: "Multi-appels séquentiels",
        categoriePrix: "standard",
      },
      {
        id: "api-03",
        titre: "API #03 — Fallback",
        description: "Retry + logging + alertes",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 5,
    slug: "google-sheets-automation",
    categorie: "basique",
    imageId: 5,
    titre: "Google Sheets Automation",
    descriptionCourte: "Sync, rapports auto, alertes, tableaux dynamiques",
    descriptionLongue: `Transformez vos Sheets en bases de données dynamiques. Synchronisation automatique, rapports générés, alertes sur conditions.`,
    outils: ["Make", "n8n", "Google Sheets API"],
    secteurs: ["finance", "ops", "marketing"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 150,
        delaiJours: 2,
        description: "Sync simple",
        features: ["1 source → Sheets", "MàJ temps réel"],
        workflows: ["CRM → Sheets"],
        livrables: ["Workflow", "Doc"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 350,
        delaiJours: 3,
        description: "Multi-sources + rapports",
        features: ["3 sources", "Rapports programmés", "Alertes conditions"],
        workflows: ["Multi-sources → Sheets", "Rapport auto"],
        livrables: ["3 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 600,
        delaiJours: 5,
        description: "Dashboard complet",
        features: [
          "Sources illimitées",
          "Dashboard interactif",
          "Webhook sortant",
        ],
        livrables: ["Dashboard Sheets", "Documentation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "sheet-01",
        titre: "Sheet #01 — Sync entrante",
        description: "CRM/Form → Sheets",
        categoriePrix: "basique",
      },
      {
        id: "sheet-02",
        titre: "Sheet #02 — Rapport auto",
        description: "Sheets → PDF → Email/Slack",
        categoriePrix: "standard",
      },
      {
        id: "sheet-03",
        titre: "Sheet #03 — Dashboard",
        description: "Query → graphique → actualisation",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 6,
    slug: "notification-automation",
    categorie: "basique",
    imageId: 6,
    titre: "Notification Automation",
    descriptionCourte: "Slack · WhatsApp · Telegram · Discord — alertes métier",
    descriptionLongue: `Centralisez toutes vos notifications métier sur les canaux que votre équipe utilise déjà.`,
    outils: ["Make", "n8n", "Slack", "WhatsApp", "Telegram"],
    secteurs: ["ops", "support", "ventes"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 180,
        delaiJours: 2,
        description: "1 canal",
        features: ["1 canal", "Alertes simples"],
        workflows: ["CRM → Slack"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 400,
        delaiJours: 3,
        description: "Multi-canaux",
        features: ["3 canaux", "Filtrage", "Routage"],
        workflows: ["Multi-canaux routing"],
        livrables: ["3 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 700,
        delaiJours: 5,
        description: "Orchestration complète",
        features: ["Canaux illimités", "Logique complexe", "Dashboard alertes"],
        livrables: ["Système complet", "Documentation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "notif-01",
        titre: "Notif #01 — Canal unique",
        description: "Événement → Slack",
        categoriePrix: "basique",
      },
      {
        id: "notif-02",
        titre: "Notif #02 — Multi-canaux",
        description: "Événement → Slack + WhatsApp + Email",
        categoriePrix: "standard",
      },
      {
        id: "notif-03",
        titre: "Notif #03 — Escalade",
        description: "Si pas réponse → escalade hiérarchique",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 7,
    slug: "ecommerce-automation",
    categorie: "basique",
    imageId: 7,
    titre: "E-commerce Automation",
    descriptionCourte: "Shopify · WooCommerce — commandes, stocks, emails",
    descriptionLongue: `Automatisez toute votre chaîne e-commerce : commandes, stocks, emails transactionnels, panier abandonné.`,
    outils: ["Make", "n8n", "Shopify", "WooCommerce", "Stripe"],
    secteurs: ["ecommerce", "retail"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        description: "Sync commandes",
        features: ["Nouvelle commande → Sheets", "Email client"],
        workflows: ["Commande → Sheets → Email"],
        livrables: ["2 workflows"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 650,
        delaiJours: 5,
        description: "Panier abandonné + stocks",
        features: [
          "Panier abandonné récupération",
          "Sync stocks multi-canaux",
          "Emails transactionnels",
        ],
        workflows: ["Panier abandonné", "Sync stocks", "Email commande"],
        livrables: ["5 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1200,
        delaiJours: 7,
        description: "Automatisation complète",
        features: [
          "Tout Standard +",
          "Prédiction stocks",
          "Upsell auto",
          "Dashboard vendeur",
        ],
        livrables: ["Système complet", "Formation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "eco-01",
        titre: "Eco #01 — Commande",
        description: "Shopify → Sheets → Email",
        categoriePrix: "basique",
      },
      {
        id: "eco-02",
        titre: "Eco #02 — Panier abandonné",
        description: "Panier → Email/SMS séquence",
        categoriePrix: "standard",
      },
      {
        id: "eco-03",
        titre: "Eco #03 — Stock",
        description: "Vente → mise à jour stocks",
        categoriePrix: "standard",
      },
      {
        id: "eco-04",
        titre: "Eco #04 — Upsell IA",
        description: "Analyse panier → suggestion produit",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 8,
    slug: "pdf-generation",
    categorie: "basique",
    imageId: 8,
    titre: "PDF & Document Generation",
    descriptionCourte: "Factures, contrats, rapports générés automatiquement",
    descriptionLongue: `Générez automatiquement des documents PDF : factures, contrats, rapports. Déclenché depuis CRM, formulaire ou API.`,
    outils: ["Make", "n8n", "Google Docs", "PDF.co"],
    secteurs: ["finance", "legal", "admin"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 2,
        features: ["Template simple", "Génération PDF"],
        workflows: ["Data → PDF → Email"],
        livrables: ["Workflow"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 450,
        delaiJours: 4,
        features: ["Multi-templates", "Archivage auto", "Signature incluse"],
        workflows: ["PDF + signature + archivage"],
        livrables: ["3 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 800,
        delaiJours: 6,
        features: ["Templates illimités", "API PDF", "Workflow validation"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "pdf-01",
        titre: "PDF #01 — Génération simple",
        description: "Template → PDF → Email",
        categoriePrix: "basique",
      },
      {
        id: "pdf-02",
        titre: "PDF #02 — Signature",
        description: "PDF → DocuSign → archivage",
        categoriePrix: "standard",
      },
      {
        id: "pdf-03",
        titre: "PDF #03 — Batch",
        description: "Multi-documents génération",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 9,
    slug: "social-media-automation",
    categorie: "basique",
    imageId: 9,
    titre: "Social Media Automation",
    descriptionCourte:
      "LinkedIn · Twitter · Instagram — publication & stats auto",
    descriptionLongue: `Programmez et automatisez vos publications sur les réseaux sociaux. Récupération automatique des statistiques.`,
    outils: ["Make", "n8n", "LinkedIn API", "Twitter API"],
    secteurs: ["marketing", "social media"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 250,
        delaiJours: 3,
        description: "1 réseau",
        features: ["1 réseau", "Planification"],
        workflows: ["Planification → publication"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 500,
        delaiJours: 5,
        description: "3 réseaux",
        features: ["3 réseaux", "Cross-posting", "Stats basiques"],
        workflows: ["Multi-réseaux", "Stats auto"],
        livrables: ["3 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 900,
        delaiJours: 7,
        description: "Réseaux illimités",
        features: [
          "Réseaux illimités",
          "IA génération contenu",
          "Veille concurrentielle",
        ],
        livrables: ["Système complet", "Formation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "social-01",
        titre: "Social #01 — Publication planifiée",
        description: "Planning → publication auto",
        categoriePrix: "basique",
      },
      {
        id: "social-02",
        titre: "Social #02 — Stats hebdo",
        description: "Récupération stats → rapport",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 10,
    slug: "ai-chatbot-support",
    categorie: "basique",
    imageId: 10,
    titre: "AI Chatbot / Support Client",
    descriptionCourte: "FAQ auto, triage tickets, escalade intelligente",
    descriptionLongue: `Déployez un assistant IA disponible 24/7. Réponse aux FAQs, triage des tickets, escalade vers un humain pour les cas complexes.`,
    outils: ["n8n", "OpenAI", "Intercom", "Slack"],
    secteurs: ["support", "ecommerce", "saas"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 4,
        description: "FAQ base",
        features: ["FAQ base", "Triage tickets"],
        workflows: ["FAQ → réponse auto"],
        livrables: ["Chatbot configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 7,
        description: "IA avancée",
        features: ["IA avancée", "Escalade auto", "Base connaissances"],
        workflows: ["Triage → escalade"],
        livrables: ["Chatbot + base connaissances"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 10,
        description: "Agent IA complet",
        features: ["Agent IA complet", "Multi-canaux", "Fine-tuning"],
        livrables: ["Système complet", "Formation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "chat-01",
        titre: "Chat #01 — FAQ auto",
        description: "Question → recherche → réponse",
        categoriePrix: "basique",
      },
      {
        id: "chat-02",
        titre: "Chat #02 — Triage tickets",
        description: "Ticket → catégorisation → assignation",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 11,
    slug: "notion-airtable-sync",
    categorie: "basique",
    imageId: 11,
    titre: "Notion / Airtable Sync",
    descriptionCourte:
      "Base reliée aux outils métier, mise à jour en temps réel",
    descriptionLongue: `Votre base Notion ou Airtable connectée à tous vos outils métier. Mise à jour en temps réel et rapports automatisés.`,
    outils: ["Make", "n8n", "Notion", "Airtable"],
    secteurs: ["ops", "product"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 2,
        description: "Sync unidirectionnelle",
        features: ["Sync unidirectionnelle"],
        workflows: ["Source → Notion"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 450,
        delaiJours: 4,
        description: "Sync bidirectionnelle",
        features: ["Sync bidirectionnelle", "MàJ temps réel"],
        workflows: ["Sync bidirectionnelle"],
        livrables: ["2 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 800,
        delaiJours: 6,
        description: "Multi-bases",
        features: ["Multi-bases", "Workflows déclenchés"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "notion-01",
        titre: "Notion #01 — Sync entrante",
        description: "CRM → Notion",
        categoriePrix: "basique",
      },
      {
        id: "notion-02",
        titre: "Notion #02 — Sync bidirectionnelle",
        description: "CRM ↔ Notion",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 12,
    slug: "client-onboarding",
    categorie: "basique",
    imageId: 12,
    titre: "Client Onboarding Automation",
    descriptionCourte: "Welcome, accès, contrat, tâches — zéro friction",
    descriptionLongue: `Automatisez l'intégralité de votre processus d'onboarding client. De la signature du contrat à la création des accès.`,
    outils: ["Make", "n8n", "Calendly", "DocuSign", "Slack"],
    secteurs: ["saas", "service", "agence"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 3,
        description: "Onboarding simple",
        features: ["Email bienvenue", "Tâches auto"],
        workflows: ["Signature → tâches"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 700,
        delaiJours: 5,
        description: "Onboarding complet",
        features: [
          "Signature contrat",
          "Création accès",
          "Planning onboarding",
        ],
        workflows: ["Signature → accès → planning"],
        livrables: ["3 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1200,
        delaiJours: 7,
        description: "Parcours complet",
        features: ["Parcours complet", "Dashboard client"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "onboard-01",
        titre: "Onboard #01 — Bienvenue",
        description: "Signature → email bienvenue",
        categoriePrix: "basique",
      },
      {
        id: "onboard-02",
        titre: "Onboard #02 — Création accès",
        description: "Contrat → création comptes",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 13,
    slug: "reporting-automatique",
    categorie: "basique",
    imageId: 13,
    titre: "Reporting Automatique",
    descriptionCourte:
      "Agrégation multi-sources, envoi automatique email/Slack",
    descriptionLongue: `Centralisez vos données depuis toutes vos sources et recevez des rapports automatiques par email ou Slack.`,
    outils: ["n8n", "Make", "Google Sheets", "Looker"],
    secteurs: ["marketing", "finance"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 250,
        delaiJours: 2,
        description: "2 sources",
        features: ["2 sources", "Email hebdo"],
        workflows: ["Sources → rapport"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 550,
        delaiJours: 4,
        description: "5 sources",
        features: ["5 sources", "PDF + Dashboard", "Alertes Slack"],
        workflows: ["Multi-sources → Dashboard"],
        livrables: ["3 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1000,
        delaiJours: 6,
        description: "Sources illimitées",
        features: ["Sources illimitées", "API reporting"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "report-01",
        titre: "Report #01 — Email hebdo",
        description: "Agrégation → email",
        categoriePrix: "basique",
      },
      {
        id: "report-02",
        titre: "Report #02 — Dashboard",
        description: "Multi-sources → Sheets",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 14,
    slug: "form-survey-automation",
    categorie: "basique",
    imageId: 14,
    titre: "Form & Survey Automation",
    descriptionCourte:
      "Typeform · Tally → CRM, email, tâche — logique conditionnelle",
    descriptionLongue: `Chaque réponse à formulaire déclenche des actions intelligentes : création dans CRM, email personnalisé, assignation de tâche.`,
    outils: ["Make", "n8n", "Typeform", "Tally"],
    secteurs: ["marketing", "rh"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 180,
        delaiJours: 2,
        description: "1 form → CRM",
        features: ["1 form → CRM"],
        workflows: ["Form → CRM"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 400,
        delaiJours: 3,
        description: "Multi-forms",
        features: ["Multi-forms", "Logique conditionnelle", "Tâches auto"],
        workflows: ["Form → CRM → tâches"],
        livrables: ["3 workflows"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 700,
        delaiJours: 5,
        description: "Forms illimités",
        features: ["Forms illimités", "IA analyse réponses"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "form-01",
        titre: "Form #01 — CRM sync",
        description: "Formulaire → CRM",
        categoriePrix: "basique",
      },
      {
        id: "form-02",
        titre: "Form #02 — Tâches auto",
        description: "Formulaire → tâches Notion/Slack",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 15,
    slug: "esignature-automation",
    categorie: "basique",
    imageId: 15,
    titre: "E-signature Automation",
    descriptionCourte: "DocuSign · PandaDoc déclenché depuis CRM ou formulaire",
    descriptionLongue: `Automatisez l'envoi de documents à signer. Déclenché depuis votre CRM ou formulaire, avec suivi et actions post-signature.`,
    outils: ["Make", "n8n", "DocuSign", "PandaDoc"],
    secteurs: ["legal", "ventes"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 250,
        delaiJours: 2,
        description: "Envoi auto",
        features: ["Envoi auto document"],
        workflows: ["CRM → DocuSign"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 500,
        delaiJours: 4,
        description: "Suivi signature",
        features: ["Suivi signature", "Actions post-signature"],
        workflows: ["Signature → actions"],
        livrables: ["2 workflows"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 900,
        delaiJours: 6,
        description: "Multi-étapes",
        features: ["Workflow signature multi-étapes"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "esign-01",
        titre: "E-sign #01 — Envoi",
        description: "Devis → DocuSign",
        categoriePrix: "basique",
      },
      {
        id: "esign-02",
        titre: "E-sign #02 — Post-signature",
        description: "Signature → CRM + facture",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 16,
    slug: "payment-billing",
    categorie: "basique",
    imageId: 16,
    titre: "Payment & Billing Automation",
    descriptionCourte: "Stripe → facture, email, CRM — zéro action manuelle",
    descriptionLongue: `Automatisez toute votre chaîne de facturation. Paiement Stripe → génération facture → email client → mise à jour CRM.`,
    outils: ["n8n", "Make", "Stripe", "QuickBooks"],
    secteurs: ["ecommerce", "saas"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        description: "Paiement → facture",
        features: ["Paiement → facture"],
        workflows: ["Stripe → facture"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 600,
        delaiJours: 5,
        description: "Facture + CRM",
        features: ["Facture + CRM + relances"],
        workflows: ["Paiement → facture → CRM"],
        livrables: ["2 workflows"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1200,
        delaiJours: 7,
        description: "Billing complet",
        features: ["Billing complet + compta"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "bill-01",
        titre: "Bill #01 — Facturation",
        description: "Stripe → facture PDF",
        categoriePrix: "basique",
      },
      {
        id: "bill-02",
        titre: "Bill #02 — CRM sync",
        description: "Paiement → mise à jour CRM",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 17,
    slug: "data-scraping",
    categorie: "basique",
    imageId: 17,
    titre: "Data Scraping Pipeline",
    descriptionCourte: "Extraction web → structuration → base de données auto",
    descriptionLongue: `Pipeline complet de scraping web : extraction, nettoyage, structuration et injection dans votre base de données.`,
    outils: ["n8n", "Apify", "Puppeteer"],
    secteurs: ["ecommerce", "marketing"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 4,
        description: "1 source",
        features: ["1 source → CSV"],
        workflows: ["Scraping → CSV"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 900,
        delaiJours: 6,
        description: "Multi-sources",
        features: ["Multi-sources", "Nettoyage auto", "DB"],
        workflows: ["Scraping → nettoyage → DB"],
        livrables: ["3 workflows"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1800,
        delaiJours: 10,
        description: "Pipeline complet",
        features: ["Pipeline complet", "Monitoring", "Maintenance"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "scrape-01",
        titre: "Scrape #01 — Extraction",
        description: "URL → données brutes",
        categoriePrix: "basique",
      },
      {
        id: "scrape-02",
        titre: "Scrape #02 — Nettoyage",
        description: "Brut → structuré",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 18,
    slug: "recrutement-auto",
    categorie: "basique",
    imageId: 18,
    titre: "Recrutement Automation",
    descriptionCourte: "CV parsing, scoring candidats, notif équipe, ATS sync",
    descriptionLongue: `Automatisez votre process de recrutement : parsing des CV, scoring automatique, notification de l'équipe, synchronisation ATS.`,
    outils: ["Make", "n8n", "OpenAI"],
    secteurs: ["rh", "recrutement"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 3,
        description: "Parsing simple",
        features: ["CV parsing simple"],
        workflows: ["CV → données"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 750,
        delaiJours: 5,
        description: "Parsing + scoring",
        features: ["CV parsing + scoring", "ATS sync"],
        workflows: ["CV → scoring → ATS"],
        livrables: ["2 workflows"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1500,
        delaiJours: 8,
        description: "Pipeline complet IA",
        features: ["Pipeline complet IA", "Dashboard recrutement"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "recruit-01",
        titre: "Recruit #01 — Parsing CV",
        description: "CV → données structurées",
        categoriePrix: "basique",
      },
      {
        id: "recruit-02",
        titre: "Recruit #02 — Scoring IA",
        description: "CV → score → priorisation",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 19,
    slug: "booking-calendar",
    categorie: "basique",
    imageId: 19,
    titre: "Booking & Calendar Automation",
    descriptionCourte: "Calendly/Cal.com → CRM, email, Zoom, rappels SMS",
    descriptionLongue: `Chaque réservation déclenche tout le processus : création dans CRM, email de confirmation, lien Zoom généré, rappels SMS.`,
    outils: ["Make", "n8n", "Calendly", "Zoom"],
    secteurs: ["service", "sante"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 2,
        description: "RDV → Email",
        features: ["RDV → Email confirmation"],
        workflows: ["RDV → email"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 450,
        delaiJours: 4,
        description: "RDV → CRM + Zoom",
        features: ["RDV → CRM + Zoom + rappels"],
        workflows: ["RDV → CRM → Zoom → SMS"],
        livrables: ["2 workflows"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 800,
        delaiJours: 6,
        description: "Multi-agents",
        features: ["Multi-agents", "Smart scheduling"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "book-01",
        titre: "Book #01 — Confirmation",
        description: "RDV → email + SMS",
        categoriePrix: "basique",
      },
      {
        id: "book-02",
        titre: "Book #02 — CRM sync",
        description: "RDV → création CRM",
        categoriePrix: "standard",
      },
    ],
  },
  {
    id: 20,
    slug: "ai-content-generation",
    categorie: "basique",
    imageId: 20,
    titre: "AI Content Generation",
    descriptionCourte:
      "Articles, posts, descriptions produit — générés et publiés auto",
    descriptionLongue: `Générez automatiquement du contenu avec l'IA : articles, posts réseaux sociaux, descriptions produit. Planification et publication incluses.`,
    outils: ["n8n", "OpenAI", "WordPress"],
    secteurs: ["marketing", "content"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        description: "Génération article",
        features: ["Génération article", "Publication manuelle"],
        workflows: ["IA → article"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 650,
        delaiJours: 5,
        description: "Multi-contenus",
        features: ["Multi-contenus", "Planification", "SEO basique"],
        workflows: ["IA → contenu → planning"],
        livrables: ["3 workflows"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1200,
        delaiJours: 7,
        description: "Pipeline complet",
        features: ["Pipeline contenu IA complet", "Multi-plateformes"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "content-01",
        titre: "Content #01 — Article",
        description: "Prompt → article WordPress",
        categoriePrix: "basique",
      },
      {
        id: "content-02",
        titre: "Content #02 — Multi-plateformes",
        description: "Contenu → blog + social",
        categoriePrix: "standard",
      },
    ],
  },
];
