// lib/offres/basics.ts
import type { OffreComplet } from "./types";

const workflowsCommuns = {
  basiques: [
    {
      id: "wf-01",
      titre: "Workflow #01 — Sync entrante",
      description:
        "Création/Lead → Notif Slack → Google Sheets → Email bienvenue",
      categoriePrix: "basique" as const,
    },
    {
      id: "wf-02",
      titre: "Workflow #02 — Validation manuelle",
      description: "Entrée → validation humaine → actions conditionnelles",
      categoriePrix: "basique" as const,
    },
  ],
  standards: [
    {
      id: "wf-03",
      titre: "Workflow #03 — Logique conditionnelle",
      description: "Branchement selon valeur champ → actions différentes",
      categoriePrix: "standard" as const,
    },
    {
      id: "wf-04",
      titre: "Workflow #04 — Reporting automatique",
      description: "Aggrégation données → rapport PDF → Slack/Email",
      categoriePrix: "standard" as const,
    },
  ],
  pros: [
    {
      id: "wf-05",
      titre: "Workflow #05 — IA avancée",
      description: "Analyse IA → décision auto → actions contextuelles",
      categoriePrix: "pro" as const,
    },
    {
      id: "wf-06",
      titre: "Workflow #06 — Orchestration multi-étapes",
      description: "Chaîne complexe avec fallbacks et retry",
      categoriePrix: "pro" as const,
    },
  ],
};

export const basicsOffres: OffreComplet[] = [
  {
    id: 1,
    slug: "crm-automation",
    categorie: "basique",
    imageId: 1,
    titre: "Automatisation CRM",
    descriptionCourte:
      "HubSpot, Salesforce ou GHL — sync contacts, pipelines, notifications",
    descriptionLongue: `Votre CRM connecté automatiquement à vos emails, Slack, Google Sheets et outils de facturation. Les données circulent sans intervention manuelle.`,
    outils: [
      "Make",
      "n8n",
      "HubSpot",
      "Salesforce",
      "GHL",
      "Slack",
      "Google Sheets",
    ],
    secteurs: ["ventes", "marketing", "saas"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        description: "1 CRM + 2 outils connectés",
        features: [
          "Sync contacts",
          "Notifications Slack",
          "Google Sheets update",
        ],
        missingFeatures: ["Logique conditionnelle", "Reporting auto"],
        workflows: ["Sync CRM → Sheets", "Alertes Slack"],
        livrables: ["2 workflows", "Doc PDF"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 600,
        delaiJours: 5,
        description: "1 CRM + 5 outils",
        features: [
          "Multi-outils",
          "Logique conditionnelle",
          "Reporting basique",
        ],
        workflows: ["Sync CRM → Sheets", "Alertes Slack", "Logique conditions"],
        livrables: ["5 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1200,
        delaiJours: 7,
        description: "Multi-CRM + workflows complexes",
        features: [
          "Multi-CRM",
          "Workflows avancés",
          "Dashboard temps réel",
          "Support prioritaire",
        ],
        workflows: ["Tous workflows", "Orchestration avancée"],
        livrables: ["Tous workflows", "Doc + formation", "Support 30j"],
        supportJours: 30,
      },
    ],
    workflows: [
      ...workflowsCommuns.basiques,
      ...workflowsCommuns.standards,
      ...workflowsCommuns.pros,
    ],
  },
  {
    id: 2,
    slug: "email-automation",
    categorie: "basique",
    imageId: 2,
    titre: "Email Automation",
    descriptionCourte: "Séquences, relances, tri IA, réponses automatiques",
    descriptionLongue: `Vos emails partent seuls, au bon moment, au bon contact. Séquences de vente, relances intelligentes, tri de boîte mail par IA.`,
    outils: ["Make", "n8n", "Gmail API", "OpenAI", "HubSpot"],
    secteurs: ["marketing", "ventes", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 3,
        description: "1 séquence email",
        features: [
          "1 séquence (3 emails)",
          "Déclencheur formulaire/CRM",
          "Relance 1 niveau",
        ],
        missingFeatures: ["Tri IA", "Réponses auto IA"],
        workflows: ["Séquence bienvenue", "Relance simple"],
        livrables: ["2 JSONs", "Doc PDF"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 450,
        delaiJours: 5,
        description: "Séquences multi-étapes",
        features: [
          "3 séquences (5 emails)",
          "Logique conditionnelle",
          "Relances 3 niveaux",
          "Sync CRM",
          "Reporting hebdo",
        ],
        workflows: [
          "Séquences bienvenue",
          "Relances",
          "Conditionnelle",
          "Post-achat",
          "Reporting",
        ],
        livrables: ["5 JSONs", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 900,
        delaiJours: 7,
        description: "IA avancée",
        features: [
          "Tri IA boîte mail",
          "Réponses auto IA",
          "Détection intention",
          "Escalade mécontent",
          "A/B testing",
        ],
        workflows: ["Tous workflows basiques + IA"],
        livrables: ["8 JSONs", "Doc + formation", "Clé API OpenAI"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "email-01",
        titre: "Email #01 — Séquence bienvenue",
        description:
          "Formulaire → J0 bienvenue → J3 ressource → J7 appel action",
        categoriePrix: "basique",
      },
      {
        id: "email-02",
        titre: "Email #02 — Relance non-réponse",
        description:
          "X jours sans réponse → relance douce → valeur → fermeture",
        categoriePrix: "basique",
      },
      {
        id: "email-03",
        titre: "Email #03 — Conditionnelle",
        description: "Ouvert → séquence chaude / Non ouvert → objet différent",
        categoriePrix: "standard",
      },
      {
        id: "email-04",
        titre: "Email #04 — Post-achat",
        description:
          "Achat → J0 confirmation → J1 ressources → J3 check-in → J7 upsell",
        categoriePrix: "standard",
      },
      {
        id: "email-05",
        titre: "Email #05 — Reporting hebdo",
        description: "Stats emails → Google Sheets → Slack",
        categoriePrix: "standard",
      },
      {
        id: "email-06",
        titre: "Email #06 — Tri IA",
        description: "IA détecte intention → catégorise → route",
        categoriePrix: "pro",
      },
      {
        id: "email-07",
        titre: "Email #07 — Réponse auto IA",
        description: "IA lit → génère réponse contextuelle → envoie",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 3,
    slug: "lead-generation",
    categorie: "basique",
    imageId: 3,
    titre: "Lead Generation Automation",
    descriptionCourte: "Scraping · enrichissement · injection CRM · outreach",
    descriptionLongue: `Générez des leads en continu sans effort manuel. Scraping ciblé, enrichissement, injection CRM et outreach automatique.`,
    outils: ["n8n", "Make", "Apify", "HubSpot", "Salesforce"],
    secteurs: ["ventes", "marketing", "recrutement"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 4,
        description: "1 source scraping + injection",
        features: [
          "1 source scraping",
          "Enrichissement basique",
          "Injection CRM",
        ],
        workflows: ["Scraping → CSV → CRM"],
        livrables: ["2 workflows", "Doc PDF"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 700,
        delaiJours: 6,
        description: "Multi-sources + outreach",
        features: [
          "3 sources",
          "Enrichissement avancé",
          "Injection CRM",
          "Séquence outreach",
        ],
        workflows: ["Scraping multi-sources", "Enrichissement", "Outreach"],
        livrables: ["5 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1500,
        delaiJours: 10,
        description: "Pipeline complet + IA",
        features: [
          "Sources illimitées",
          "Scoring IA leads",
          "Dashboard temps réel",
          "Maintenance incluse",
        ],
        workflows: ["Extraction IA", "Nettoyage auto", "Injection temps réel"],
        livrables: ["Pipeline complet", "Documentation", "Support 30j"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "lead-01",
        titre: "Lead #01 — Scraping simple",
        description: "Source cible → extraction → CSV",
        categoriePrix: "basique",
      },
      {
        id: "lead-02",
        titre: "Lead #02 — Enrichissement",
        description: "Email → recherche → données complètes",
        categoriePrix: "standard",
      },
      {
        id: "lead-03",
        titre: "Lead #03 — Outreach auto",
        description: "Lead → email séquence → suivi",
        categoriePrix: "standard",
      },
      {
        id: "lead-04",
        titre: "Lead #04 — Scoring IA",
        description: "Score leads → priorisation vente",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 4,
    slug: "api-webhook-integration",
    categorie: "basique",
    imageId: 4,
    titre: "API & Webhook Integration",
    descriptionCourte: "Connecter n'importe quelles apps via REST / webhooks",
    descriptionLongue: `Pas de connecteur natif ? On construit des intégrations sur mesure via API REST et webhooks. Toute app avec API peut être connectée.`,
    outils: ["n8n", "Make", "REST APIs", "Webhooks"],
    secteurs: ["tech", "saas", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 250,
        delaiJours: 3,
        description: "1 API connectée",
        features: ["1 endpoint entrant", "1 sortant", "Auth basique"],
        workflows: ["Webhook → traitement → sortie"],
        livrables: ["Workflow", "Doc API"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 500,
        delaiJours: 5,
        description: "Multi-API",
        features: ["3 APIs", "Auth avancée", "Gestion erreurs", "Logs"],
        workflows: ["Multi-API orchestration"],
        livrables: ["3 workflows", "Doc technique"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1000,
        delaiJours: 7,
        description: "API custom",
        features: [
          "API illimitées",
          "Rate limiting",
          "Webhook dashboard",
          "Monitoring",
        ],
        workflows: ["API Gateway", "Rate limiting", "Dashboard monitoring"],
        livrables: ["Plateforme intégration", "Documentation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "api-01",
        titre: "API #01 — Webhook entrant",
        description: "Reçoit data → transforme → envoie",
        categoriePrix: "basique",
      },
      {
        id: "api-02",
        titre: "API #02 — Orchestration",
        description: "Multi-appels séquentiels",
        categoriePrix: "standard",
      },
      {
        id: "api-03",
        titre: "API #03 — Fallback",
        description: "Retry + logging + alertes",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 5,
    slug: "google-sheets-automation",
    categorie: "basique",
    imageId: 5,
    titre: "Google Sheets Automation",
    descriptionCourte: "Sync, rapports auto, alertes, tableaux dynamiques",
    descriptionLongue: `Transformez vos Sheets en bases de données dynamiques. Synchronisation automatique, rapports générés, alertes sur conditions.`,
    outils: ["Make", "n8n", "Google Sheets API"],
    secteurs: ["finance", "ops", "marketing"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 150,
        delaiJours: 2,
        description: "Sync simple",
        features: ["1 source → Sheets", "MàJ temps réel"],
        workflows: ["CRM → Sheets"],
        livrables: ["Workflow", "Doc"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 350,
        delaiJours: 3,
        description: "Multi-sources + rapports",
        features: ["3 sources", "Rapports programmés", "Alertes conditions"],
        workflows: ["Multi-sources → Sheets", "Rapport auto"],
        livrables: ["3 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 600,
        delaiJours: 5,
        description: "Dashboard complet",
        features: [
          "Sources illimitées",
          "Dashboard interactif",
          "Webhook sortant",
        ],
        workflows: ["Dashboard interactif", "API Sheets", "Webhook sortant"],
        livrables: ["Dashboard Sheets", "Documentation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "sheet-01",
        titre: "Sheet #01 — Sync entrante",
        description: "CRM/Form → Sheets",
        categoriePrix: "basique",
      },
      {
        id: "sheet-02",
        titre: "Sheet #02 — Rapport auto",
        description: "Sheets → PDF → Email/Slack",
        categoriePrix: "standard",
      },
      {
        id: "sheet-03",
        titre: "Sheet #03 — Dashboard",
        description: "Query → graphique → actualisation",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 6,
    slug: "notification-automation",
    categorie: "basique",
    imageId: 6,
    titre: "Notification Automation",
    descriptionCourte: "Slack · WhatsApp · Telegram · Discord — alertes métier",
    descriptionLongue: `Centralisez toutes vos notifications métier sur les canaux que votre équipe utilise déjà.`,
    outils: ["Make", "n8n", "Slack", "WhatsApp", "Telegram"],
    secteurs: ["ops", "support", "ventes"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 180,
        delaiJours: 2,
        description: "1 canal",
        features: ["1 canal", "Alertes simples"],
        workflows: ["CRM → Slack"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 400,
        delaiJours: 3,
        description: "Multi-canaux",
        features: ["3 canaux", "Filtrage", "Routage"],
        workflows: ["Multi-canaux routing"],
        livrables: ["3 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 700,
        delaiJours: 5,
        description: "Orchestration complète",
        features: ["Canaux illimités", "Logique complexe", "Dashboard alertes"],
        workflows: ["Orchestration multi-canaux", "Dashboard alertes"],
        livrables: ["Système complet", "Documentation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "notif-01",
        titre: "Notif #01 — Canal unique",
        description: "Événement → Slack",
        categoriePrix: "basique",
      },
      {
        id: "notif-02",
        titre: "Notif #02 — Multi-canaux",
        description: "Événement → Slack + WhatsApp + Email",
        categoriePrix: "standard",
      },
      {
        id: "notif-03",
        titre: "Notif #03 — Escalade",
        description: "Si pas réponse → escalade hiérarchique",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 7,
    slug: "ecommerce-automation",
    categorie: "basique",
    imageId: 7,
    titre: "E-commerce Automation",
    descriptionCourte: "Shopify · WooCommerce — commandes, stocks, emails",
    descriptionLongue: `Automatisez toute votre chaîne e-commerce : commandes, stocks, emails transactionnels, panier abandonné.`,
    outils: ["Make", "n8n", "Shopify", "WooCommerce", "Stripe"],
    secteurs: ["ecommerce", "retail"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        description: "Sync commandes",
        features: ["Nouvelle commande → Sheets", "Email client"],
        workflows: ["Commande → Sheets → Email"],
        livrables: ["2 workflows"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 650,
        delaiJours: 5,
        description: "Panier abandonné + stocks",
        features: [
          "Panier abandonné récupération",
          "Sync stocks multi-canaux",
          "Emails transactionnels",
        ],
        workflows: ["Panier abandonné", "Sync stocks", "Email commande"],
        livrables: ["5 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1200,
        delaiJours: 7,
        description: "Automatisation complète",
        features: [
          "Tout Standard +",
          "Prédiction stocks",
          "Upsell auto",
          "Dashboard vendeur",
        ],
        workflows: ["Prédiction stocks IA", "Upsell auto", "Dashboard vendeur"],
        livrables: ["Système complet", "Formation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "eco-01",
        titre: "Eco #01 — Commande",
        description: "Shopify → Sheets → Email",
        categoriePrix: "basique",
      },
      {
        id: "eco-02",
        titre: "Eco #02 — Panier abandonné",
        description: "Panier → Email/SMS séquence",
        categoriePrix: "standard",
      },
      {
        id: "eco-03",
        titre: "Eco #03 — Stock",
        description: "Vente → mise à jour stocks",
        categoriePrix: "standard",
      },
      {
        id: "eco-04",
        titre: "Eco #04 — Upsell IA",
        description: "Analyse panier → suggestion produit",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 8,
    slug: "pdf-generation",
    categorie: "basique",
    imageId: 8,
    titre: "PDF & Document Generation",
    descriptionCourte: "Factures, contrats, rapports générés automatiquement",
    descriptionLongue: `Générez automatiquement des documents PDF : factures, contrats, rapports. Déclenché depuis CRM, formulaire ou API.`,
    outils: ["Make", "n8n", "Google Docs", "PDF.co"],
    secteurs: ["finance", "legal", "admin"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 2,
        description: "Génération simple",
        features: ["Template simple", "Génération PDF"],
        workflows: ["Data → PDF → Email"],
        livrables: ["Workflow"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 450,
        delaiJours: 4,
        description: "Multi-templates",
        features: ["Multi-templates", "Archivage auto", "Signature incluse"],
        workflows: ["PDF + signature + archivage"],
        livrables: ["3 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 800,
        delaiJours: 6,
        description: "PDF avancé",
        features: ["Templates illimités", "API PDF", "Workflow validation"],
        workflows: ["API PDF", "Workflow validation", "Batch generation"],
        livrables: ["Système complet"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "pdf-01",
        titre: "PDF #01 — Génération simple",
        description: "Template → PDF → Email",
        categoriePrix: "basique",
      },
      {
        id: "pdf-02",
        titre: "PDF #02 — Signature",
        description: "PDF → DocuSign → archivage",
        categoriePrix: "standard",
      },
      {
        id: "pdf-03",
        titre: "PDF #03 — Batch",
        description: "Multi-documents génération",
        categoriePrix: "pro",
      },
    ],
  },
  {
    id: 9,
    slug: "social-media-automation",
    categorie: "basique",
    imageId: 9,
    titre: "Social Media Automation",
    descriptionCourte:
      "LinkedIn · Twitter · Instagram — publication & stats auto",
    descriptionLongue: `Programmez et automatisez vos publications sur les réseaux sociaux. Récupération automatique des statistiques.`,
    outils: ["Make", "n8n", "LinkedIn API", "Twitter API"],
    secteurs: ["marketing", "social media"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 250,
        delaiJours: 3,
        description: "1 réseau",
        features: ["1 réseau", "Planification"],
        workflows: ["Planification → publication"],
        livrables: ["Workflow config"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 500,
        delaiJours: 5,
        description: "3 réseaux",
        features: ["3 réseaux", "Cross-posting", "Stats basiques"],
        workflows: ["Multi-réseaux", "Stats auto"],
        livrables: ["3 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 900,
        delaiJours: 7,
        description: "Réseaux illimités",
        features: [
          "Réseaux illimités",
          "IA génération contenu",
          "Veille concurrentielle",
        ],
        workflows: ["IA génération contenu", "Veille concurrentielle"],
        livrables: ["Système complet", "Formation"],
        supportJours: 30,
      },
    ],
    workflows: [
      {
        id: "social-01",
        titre: "Social #01 — Publication planifiée",
        description: "Planning → publication auto",
        categoriePrix: "basique",
      },
      {
        id: "social-02",
        titre: "Social #02 — Stats hebdo",
        description: "Récupération stats → rapport",
        categoriePrix: "standard",
      },
    ],
  },
  // ... (les offres 10 à 20 sont identiques à ce que tu as déjà,
  // assure-toi que chaque PrixTier a bien une propriété "workflows")
];

// Pour les offres 10 à 20, vérifie que chaque niveau (Basique, Standard, Pro)
// a bien la propriété "workflows". Exemple pour l'offre 10:
// {
//   nom: "Pro",
//   ...
//   workflows: ["Workflow 1", "Workflow 2"], // ← AJOUTER CETTE LIGNE
//   ...
// }
