// lib/offres/dead-angles.ts
import type { OffreComplet } from "./types";

export const deadAnglesOffres: OffreComplet[] = [
  {
    id: 41,
    slug: "ai-voice-agent",
    categorie: "angle-mort",
    imageId: 41,
    titre: "AI Voice Agent — Réceptionniste IA",
    descriptionCourte:
      "Appels entrants → RDV auto → qualification vocale → CRM",
    descriptionLongue: `Un assistant vocal intelligent qui répond à vos appels téléphoniques 24/7, qualifie les prospects, prend des rendez-vous et transmet les informations à votre CRM.`,
    outils: ["n8n", "OpenAI", "Twilio", "Calendly"],
    secteurs: ["service", "sante", "immobilier"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 1200,
        delaiJours: 7,
        features: ["Réception simple", "Transfert humain"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 2500,
        delaiJours: 10,
        features: ["Qualification vocale", "Prise RDV", "CRM sync"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 5000,
        delaiJours: 14,
        features: ["Agent IA complet", "Multi-langues", "Dashboard appels"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 42,
    slug: "retainer-maintenance",
    categorie: "angle-mort",
    imageId: 42,
    titre: "Retainer Maintenance & Monitoring",
    descriptionCourte:
      "Suivi mensuel, bugs, évolutions, rapport — revenu récurrent",
    descriptionLongue: `Service de maintenance mensuel. Surveillance des workflows, corrections d'urgence, évolutions mineures, rapport d'activité.`,
    outils: ["n8n", "Make", "Slack", "Airtable"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 0,
        features: ["Surveillance base", "Support 48h"],
        supportJours: 30,
        popular: true,
      },
      {
        nom: "Standard",
        prix: 500,
        delaiJours: 0,
        features: [
          "Monitoring avancé",
          "Évolutions incluses",
          "Rapport mensuel",
        ],
        supportJours: 30,
      },
      {
        nom: "Pro",
        prix: 1000,
        delaiJours: 0,
        features: ["SLA 4h", "Dédié", "Audit trimestriel"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 43,
    slug: "audit-automation-pme",
    categorie: "angle-mort",
    imageId: 43,
    titre: "Audit Automation PME",
    descriptionCourte:
      "Diagnostic processus, gains chiffrés, plan priorisé livré",
    descriptionLongue: `Audit complet de vos processus métier. Identification des opportunités d'automatisation, gains chiffrés, roadmap priorisée.`,
    outils: ["Miro", "Google Sheets"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Unique",
        prix: 150,
        delaiJours: 3,
        features: ["Audit complet", "Rapport gains", "Roadmap"],
        supportJours: 7,
        popular: true,
      },
    ],
    workflows: [],
  },
  {
    id: 44,
    slug: "juridique-actes-relances",
    categorie: "angle-mort",
    imageId: 44,
    titre: "Juridique — Actes & Relances Auto",
    descriptionCourte:
      "Actes standard, Docusign, relances, classement dossiers",
    descriptionLongue: `Solution pour cabinets juridiques : génération d'actes standard, signature électronique, relances clients, classement automatique.`,
    outils: ["Make", "DocuSign", "Dropbox", "Slack"],
    secteurs: ["juridique", "legal"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 800,
        delaiJours: 5,
        features: ["Actes standard", "DocuSign"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1800,
        delaiJours: 8,
        features: ["Multi-actes", "Relances auto", "Classement"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3500,
        delaiJours: 12,
        features: ["IA génération", "Portail client", "Timeline affaire"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 45,
    slug: "templates-workflows",
    categorie: "angle-mort",
    imageId: 45,
    titre: "Vente de Templates Workflows",
    descriptionCourte:
      "Packs sectoriels prêts à l'emploi — modèle produit digital",
    descriptionLongue: `Templates Make/n8n prêts à l'emploi pour divers secteurs. Installation en 5 minutes, documentation incluse.`,
    outils: ["Make", "n8n"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Pack Solo",
        prix: 47,
        delaiJours: 0,
        features: ["1 template", "Doc PDF"],
        supportJours: 7,
        popular: true,
      },
      {
        nom: "Pack Pro",
        prix: 147,
        delaiJours: 0,
        features: ["5 templates", "Doc + vidéo", "Support email"],
        supportJours: 14,
      },
      {
        nom: "Pack Enterprise",
        prix: 297,
        delaiJours: 0,
        features: ["15 templates", "Support prioritaire", "1h coaching"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 46,
    slug: "marche-africain-francophone",
    categorie: "angle-mort",
    imageId: 46,
    titre: "Marché Africain Francophone",
    descriptionCourte: "WhatsApp Business, Mobile Money, FR — offre localisée",
    descriptionLongue: `Solutions localisées pour l'Afrique francophone. Intégration WhatsApp Business, Mobile Money, Orange Money, support en français.`,
    outils: ["Make", "WhatsApp", "Mobile Money API"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 3,
        features: ["WhatsApp auto", "SMS local"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Standard",
        prix: 500,
        delaiJours: 5,
        features: ["Multi-canaux", "Paiement Mobile Money", "CRM sync"],
        supportJours: 21,
      },
      {
        nom: "Pro",
        prix: 1200,
        delaiJours: 7,
        features: ["Solution complète", "Support FR dédié", "Formation équipe"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 47,
    slug: "rag-agent-docs",
    categorie: "angle-mort",
    imageId: 47,
    titre: "RAG Agent — Base Docs Interne",
    descriptionCourte:
      "Chatbot sur PDF/Notion/Drive — réponses contextuelles IA",
    descriptionLongue: `Agent IA qui répond aux questions sur votre documentation interne (PDF, Notion, Google Drive). Recherche contextuelle précise.`,
    outils: ["n8n", "OpenAI", "Pinecone", "Notion"],
    secteurs: ["rh", "support", "legal"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 1000,
        delaiJours: 5,
        features: ["1 source", "Réponses basiques"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 2500,
        delaiJours: 8,
        features: ["3 sources", "Réponses précises", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 5000,
        delaiJours: 12,
        features: ["Sources illimitées", "Fine-tuning", "API publique"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 48,
    slug: "btp-suivi-chantier",
    categorie: "angle-mort",
    imageId: 48,
    titre: "BTP — Suivi Chantier Automatisé",
    descriptionCourte:
      "Photos terrain → rapport → alertes retard → facture étapes",
    descriptionLongue: `Solution pour le BTP : suivi chantier automatisé, rapports photo, alertes retard, facturation par étape.`,
    outils: ["Make", "WhatsApp", "Google Drive", "QuickBooks"],
    secteurs: ["btp", "construction"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 700,
        delaiJours: 5,
        features: ["Photos → Drive", "Rapport hebdo"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 7,
        features: ["Alertes retard", "Facture étapes", "Dashboard chantier"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 10,
        features: [
          "Multi-chantiers",
          "IA détection anomalies",
          "Portail client",
        ],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 49,
    slug: "veille-concurrentielle-ia",
    categorie: "angle-mort",
    imageId: 49,
    titre: "Veille Concurrentielle IA",
    descriptionCourte: "Prix, offres, avis, mentions — rapport quotidien auto",
    descriptionLongue: `Veille concurrentielle automatisée par IA. Surveillance prix, offres, avis, mentions sur le web. Rapport quotidien.`,
    outils: ["n8n", "OpenAI", "Apify", "Google Sheets"],
    secteurs: ["marketing", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 4,
        features: ["1 concurrent", "Rapport hebdo"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1400,
        delaiJours: 6,
        features: ["5 concurrents", "Alertes temps réel", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2800,
        delaiJours: 8,
        features: ["Concurrents illimités", "IA analyse", "API veille"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 50,
    slug: "logistique-suivi-facturation",
    categorie: "angle-mort",
    imageId: 50,
    titre: "Logistique — Suivi & Facturation",
    descriptionCourte: "Colis, livreur, POD, facturation à la livraison — auto",
    descriptionLongue: `Solution logistique complète : suivi colis, gestion livreur, POD électronique, facturation déclenchée à la livraison.`,
    outils: ["n8n", "Shipstation", "Stripe", "Twilio"],
    secteurs: ["logistique", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 5,
        features: ["Suivi colis", "Notif client"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 7,
        features: ["Multi-transporteurs", "POD auto", "Facturation"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 10,
        features: [
          "Flotte complète",
          "Optimisation tournées",
          "Dashboard logistique",
        ],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 51,
    slug: "lead-scoring-ia",
    categorie: "angle-mort",
    imageId: 51,
    titre: "Lead Scoring IA Automatique",
    descriptionCourte:
      "Comportement → score IA → prioritisation équipe commerciale",
    descriptionLongue: `Score automatique des leads basé sur leur comportement. Priorisation de l'équipe commerciale.`,
    outils: ["n8n", "OpenAI", "HubSpot", "Slack"],
    secteurs: ["ventes", "marketing"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 800,
        delaiJours: 4,
        features: ["Score simple", "CRM sync"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1800,
        delaiJours: 6,
        features: ["Multi-critères", "IA avancée", "Alertes chaud"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3500,
        delaiJours: 8,
        features: ["Prédiction conversion", "Dashboard vente", "API scoring"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 52,
    slug: "rh-onboarding-employe",
    categorie: "angle-mort",
    imageId: 52,
    titre: "RH — Onboarding Employé",
    descriptionCourte:
      "Embauche → accès → formation → congés → offboarding auto",
    descriptionLongue: `Parcours employé automatisé : onboarding, création accès, formation, gestion congés, offboarding.`,
    outils: ["Make", "Slack", "Notion", "Google Workspace"],
    secteurs: ["rh", "entreprise"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 700,
        delaiJours: 5,
        features: ["Embauche → accès", "Email bienvenue"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 7,
        features: ["Parcours complet", "Formation auto", "Congés"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 10,
        features: ["Plateforme RH", "Évaluations", "Analytics talent"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 53,
    slug: "agriculture-alertes",
    categorie: "angle-mort",
    imageId: 53,
    titre: "Agriculture — Alertes & Commandes",
    descriptionCourte: "Météo, irrigation, commandes, rapports récolte — auto",
    descriptionLongue: `Solutions agricoles : alertes météo, pilotage irrigation, gestion commandes, rapports récolte automatisés.`,
    outils: ["n8n", "OpenWeather", "Twilio"],
    secteurs: ["agriculture"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 4,
        features: ["Alertes météo", "SMS commande"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 6,
        features: ["Irrigation auto", "Dashboard récolte", "Prévisions"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 8,
        features: ["Ferme connectée", "IA prédictive", "Marketplace"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 54,
    slug: "referral-parrainage",
    categorie: "angle-mort",
    imageId: 54,
    titre: "Referral & Parrainage Automatisé",
    descriptionCourte:
      "Parrainage → suivi → récompense → rapport conversion auto",
    descriptionLongue: `Programme de parrainage automatisé. Suivi des filleuls, attribution récompenses, rapports conversion.`,
    outils: ["Make", "Stripe", "Mailgun", "Airtable"],
    secteurs: ["saas", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 3,
        features: ["Lien parrainage", "Email bienvenue"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 5,
        features: ["Suivi conversion", "Récompense auto", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 7,
        features: ["Multi-niveaux", "IA optimisation", "API partenaire"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 55,
    slug: "migration-nettoyage",
    categorie: "angle-mort",
    imageId: 55,
    titre: "Migration & Nettoyage Workflows",
    descriptionCourte: "Reprise workflows cassés Make/Zapier — audit + rebuild",
    descriptionLongue: `Audit et migration de vos workflows existants (Make, Zapier). Reconstruction propre, documentation, transfert.`,
    outils: ["Make", "n8n", "Zapier"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        features: ["Audit", "1 workflow migré"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Standard",
        prix: 800,
        delaiJours: 5,
        features: ["5 workflows", "Documentation", "Tests"],
        supportJours: 21,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 7,
        features: ["Migration complète", "Optimisation", "Formation"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 56,
    slug: "evenementiel-inscriptions",
    categorie: "angle-mort",
    imageId: 56,
    titre: "Événementiel — Gestion Inscriptions",
    descriptionCourte: "Inscrip. → badge → rappel → feedback → certificat auto",
    descriptionLongue: `Solution événementielle : inscriptions, génération badges, rappels, feedback post-événement, certificats.`,
    outils: ["Make", "Tito", "Canva API", "Mailgun"],
    secteurs: ["event", "conference"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 450,
        delaiJours: 3,
        features: ["Inscriptions", "Email rappel"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 5,
        features: ["Badge PDF", "Feedback auto", "Certificat"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 7,
        features: ["Check-in QR code", "Mobile app", "Analytics event"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 57,
    slug: "syndic-copropriete",
    categorie: "angle-mort",
    imageId: 57,
    titre: "Syndic / Copropriété — Gestion Auto",
    descriptionCourte:
      "AG, charges, travaux, comms copropriétaires — automatisés",
    descriptionLongue: `Solution pour syndics : gestion AG, appels de charges, suivi travaux, communications copropriétaires.`,
    outils: ["Make", "WhatsApp", "Stripe", "Google Drive"],
    secteurs: ["immobilier", "syndic"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 4,
        features: ["Appels charges", "Email copros"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1400,
        delaiJours: 6,
        features: ["AG digitale", "Suivi travaux", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2800,
        delaiJours: 10,
        features: ["Portail copro", "Paiement CB", "Maintenance prédictive"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 58,
    slug: "newsletter-ia",
    categorie: "angle-mort",
    imageId: 58,
    titre: "Newsletter IA Personnalisée",
    descriptionCourte:
      "Contenu IA selon profil lecteur, envoi segmenté, stats auto",
    descriptionLongue: `Newsletter générée par IA, personnalisée selon les préférences lecteur. Segmentation automatique, stats détaillées.`,
    outils: ["n8n", "OpenAI", "ConvertKit", "Supabase"],
    secteurs: ["marketing", "media"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 4,
        features: ["Génération contenu", "Envoi segmenté"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 6,
        features: ["Personnalisation", "A/B testing", "Dashboard stats"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 8,
        features: ["Multi-nl", "IA fine-tuning", "Monétisation auto"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 59,
    slug: "veille-appels-offres-ia",
    categorie: "angle-mort",
    imageId: 59,
    titre: "Veille Appels d'Offres IA",
    descriptionCourte: "Marchés publics → scoring IA → alerte équipe — auto",
    descriptionLongue: `Veille automatisée des appels d'offres. Scraping, scoring par IA, alertes équipe commerciale.`,
    outils: ["n8n", "OpenAI", "Slack", "Airtable"],
    secteurs: ["b2b", "public"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 700,
        delaiJours: 5,
        features: ["1 source", "Alerte email"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 7,
        features: ["3 sources", "Scoring IA", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 10,
        features: ["Sources illimitées", "Réponse IA", "API veille"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 60,
    slug: "reputation-avis",
    categorie: "angle-mort",
    imageId: 60,
    titre: "Réputation — Avis Multi-Plateforme",
    descriptionCourte:
      "Post-achat → Google/Trustpilot → modération IA → réponse",
    descriptionLongue: `Gestion automatisée des avis clients. Demande post-achat, modération IA, réponses automatiques.`,
    outils: ["Make", "OpenAI", "Google Reviews API", "Trustpilot API"],
    secteurs: ["ecommerce", "service"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 3,
        features: ["Demande avis email", "Réponse auto"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 5,
        features: ["Multi-plateformes", "Modération IA", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 7,
        features: ["IA avancée", "Curation avis", "API réputation"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
];
