// lib/offres/dead-angles.ts
import type { OffreComplet } from "./types";

export const deadAnglesOffres: OffreComplet[] = [
  {
    id: 41,
    slug: "ai-voice-agent",
    categorie: "angle-mort",
    imageId: 41,
    titre: "AI Voice Agent — Réceptionniste IA",
    descriptionCourte:
      "Appels entrants → RDV auto → qualification vocale → CRM",
    descriptionLongue: `Un assistant vocal intelligent qui répond à vos appels téléphoniques 24/7, qualifie les prospects, prend des rendez-vous et transmet les informations à votre CRM.`,
    outils: ["n8n", "OpenAI", "Twilio", "Calendly"],
    secteurs: ["service", "sante", "immobilier"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 1200,
        delaiJours: 7,
        description: "Réception simple",
        features: ["Réception simple", "Transfert humain"],
        workflows: ["Réception → Transfert"],
        livrables: ["Workflow configuré", "Documentation"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 2500,
        delaiJours: 10,
        description: "Qualification vocale",
        features: ["Qualification vocale", "Prise RDV", "CRM sync"],
        workflows: ["Appel → Qualification → RDV → CRM"],
        livrables: ["3 workflows", "Doc PDF", "Support prioritaire"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 5000,
        delaiJours: 14,
        description: "Agent IA complet",
        features: ["Agent IA complet", "Multi-langues", "Dashboard appels"],
        workflows: ["Agent vocal complet", "Analytics appels", "Multi-langues"],
        livrables: ["Système complet", "Formation", "Support dédié"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 42,
    slug: "retainer-maintenance",
    categorie: "angle-mort",
    imageId: 42,
    titre: "Retainer Maintenance & Monitoring",
    descriptionCourte:
      "Suivi mensuel, bugs, évolutions, rapport — revenu récurrent",
    descriptionLongue: `Service de maintenance mensuel. Surveillance des workflows, corrections d'urgence, évolutions mineures, rapport d'activité.`,
    outils: ["n8n", "Make", "Slack", "Airtable"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 0,
        description: "Surveillance base",
        features: ["Surveillance base", "Support 48h"],
        workflows: ["Monitoring basique"],
        livrables: ["Rapport mensuel"],
        supportJours: 30,
        popular: true,
      },
      {
        nom: "Standard",
        prix: 500,
        delaiJours: 0,
        description: "Monitoring avancé",
        features: [
          "Monitoring avancé",
          "Évolutions incluses",
          "Rapport mensuel",
        ],
        workflows: ["Monitoring avancé", "Rapport hebdo"],
        livrables: ["Dashboard", "Support prioritaire"],
        supportJours: 30,
      },
      {
        nom: "Pro",
        prix: 1000,
        delaiJours: 0,
        description: "SLA dédié",
        features: ["SLA 4h", "Dédié", "Audit trimestriel"],
        workflows: ["Monitoring 24/7", "Alertes temps réel", "Audit"],
        livrables: ["SLA personnalisé", "Support dédié", "Dashboard"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 43,
    slug: "audit-automation-pme",
    categorie: "angle-mort",
    imageId: 43,
    titre: "Audit Automation PME",
    descriptionCourte:
      "Diagnostic processus, gains chiffrés, plan priorisé livré",
    descriptionLongue: `Audit complet de vos processus métier. Identification des opportunités d'automatisation, gains chiffrés, roadmap priorisée.`,
    outils: ["Miro", "Google Sheets"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Standard",
        prix: 150,
        delaiJours: 3,
        description: "Audit complet",
        features: ["Audit complet", "Rapport gains", "Roadmap"],
        workflows: ["Audit → Analyse → Recommandations"],
        livrables: ["Rapport audit", "Roadmap priorisée"],
        supportJours: 7,
        popular: true,
      },
    ],
    workflows: [],
  },
  {
    id: 44,
    slug: "juridique-actes-relances",
    categorie: "angle-mort",
    imageId: 44,
    titre: "Juridique — Actes & Relances Auto",
    descriptionCourte:
      "Actes standard, Docusign, relances, classement dossiers",
    descriptionLongue: `Solution pour cabinets juridiques : génération d'actes standard, signature électronique, relances clients, classement automatique.`,
    outils: ["Make", "DocuSign", "Dropbox", "Slack"],
    secteurs: ["juridique", "legal"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 800,
        delaiJours: 5,
        description: "Actes standard",
        features: ["Actes standard", "DocuSign"],
        workflows: ["Génération acte → Signature"],
        livrables: ["Workflow configuré", "Doc PDF"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1800,
        delaiJours: 8,
        description: "Multi-actes",
        features: ["Multi-actes", "Relances auto", "Classement"],
        workflows: ["Multi-actes", "Relances", "Archivage"],
        livrables: ["3 workflows", "Doc + vidéo"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3500,
        delaiJours: 12,
        description: "IA génération",
        features: ["IA génération", "Portail client", "Timeline affaire"],
        workflows: ["IA génération", "Portail client", "Dashboard"],
        livrables: ["Système complet", "Formation"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 45,
    slug: "templates-workflows",
    categorie: "angle-mort",
    imageId: 45,
    titre: "Vente de Templates Workflows",
    descriptionCourte:
      "Packs sectoriels prêts à l'emploi — modèle produit digital",
    descriptionLongue: `Templates Make/n8n prêts à l'emploi pour divers secteurs. Installation en 5 minutes, documentation incluse.`,
    outils: ["Make", "n8n"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 47,
        delaiJours: 0,
        description: "1 template",
        features: ["1 template", "Doc PDF"],
        workflows: ["1 template prêt à l'emploi"],
        livrables: ["Template", "Documentation"],
        supportJours: 7,
        popular: true,
      },
      {
        nom: "Standard",
        prix: 147,
        delaiJours: 0,
        description: "5 templates",
        features: ["5 templates", "Doc + vidéo", "Support email"],
        workflows: ["5 templates", "Formation vidéo"],
        livrables: ["Pack de 5 templates", "Support email"],
        supportJours: 14,
      },
      {
        nom: "Pro",
        prix: 297,
        delaiJours: 0,
        description: "15 templates",
        features: ["15 templates", "Support prioritaire", "1h coaching"],
        workflows: ["15 templates", "Coaching personnalisé"],
        livrables: ["Pack complet", "Coaching 1h", "Support prioritaire"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 46,
    slug: "marche-africain-francophone",
    categorie: "angle-mort",
    imageId: 46,
    titre: "Marché Africain Francophone",
    descriptionCourte: "WhatsApp Business, Mobile Money, FR — offre localisée",
    descriptionLongue: `Solutions localisées pour l'Afrique francophone. Intégration WhatsApp Business, Mobile Money, Orange Money, support en français.`,
    outils: ["Make", "WhatsApp", "Mobile Money API"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 200,
        delaiJours: 3,
        description: "WhatsApp auto",
        features: ["WhatsApp auto", "SMS local"],
        workflows: ["WhatsApp notification"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Standard",
        prix: 500,
        delaiJours: 5,
        description: "Multi-canaux",
        features: ["Multi-canaux", "Paiement Mobile Money", "CRM sync"],
        workflows: ["Multi-canaux → CRM"],
        livrables: ["3 workflows", "Documentation"],
        supportJours: 21,
      },
      {
        nom: "Pro",
        prix: 1200,
        delaiJours: 7,
        description: "Solution complète",
        features: ["Solution complète", "Support FR dédié", "Formation équipe"],
        workflows: ["Solution complète AF", "Dashboard suivi"],
        livrables: ["Système complet", "Formation équipe"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 47,
    slug: "rag-agent-docs",
    categorie: "angle-mort",
    imageId: 47,
    titre: "RAG Agent — Base Docs Interne",
    descriptionCourte:
      "Chatbot sur PDF/Notion/Drive — réponses contextuelles IA",
    descriptionLongue: `Agent IA qui répond aux questions sur votre documentation interne (PDF, Notion, Google Drive). Recherche contextuelle précise.`,
    outils: ["n8n", "OpenAI", "Pinecone", "Notion"],
    secteurs: ["rh", "support", "legal"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 1000,
        delaiJours: 5,
        description: "1 source",
        features: ["1 source", "Réponses basiques"],
        workflows: ["Source → Embedding → Chat"],
        livrables: ["Chatbot configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 2500,
        delaiJours: 8,
        description: "3 sources",
        features: ["3 sources", "Réponses précises", "Dashboard"],
        workflows: ["Multi-sources → RAG → Chat + Dashboard"],
        livrables: ["Chatbot avancé", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 5000,
        delaiJours: 12,
        description: "Sources illimitées",
        features: ["Sources illimitées", "Fine-tuning", "API publique"],
        workflows: ["Sources illimitées", "Fine-tuning IA", "API REST"],
        livrables: ["Solution complète", "API", "Formation"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 48,
    slug: "btp-suivi-chantier",
    categorie: "angle-mort",
    imageId: 48,
    titre: "BTP — Suivi Chantier Automatisé",
    descriptionCourte:
      "Photos terrain → rapport → alertes retard → facture étapes",
    descriptionLongue: `Solution pour le BTP : suivi chantier automatisé, rapports photo, alertes retard, facturation par étape.`,
    outils: ["Make", "WhatsApp", "Google Drive", "QuickBooks"],
    secteurs: ["btp", "construction"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 700,
        delaiJours: 5,
        description: "Photos → Drive",
        features: ["Photos → Drive", "Rapport hebdo"],
        workflows: ["Photos → Drive → Rapport"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 7,
        description: "Alertes retard",
        features: ["Alertes retard", "Facture étapes", "Dashboard chantier"],
        workflows: ["Photos → Drive → Alertes → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 10,
        description: "Multi-chantiers",
        features: [
          "Multi-chantiers",
          "IA détection anomalies",
          "Portail client",
        ],
        workflows: ["Multi-chantiers", "IA anomalies", "Portail client"],
        livrables: ["Système complet", "Portail client"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 49,
    slug: "veille-concurrentielle-ia",
    categorie: "angle-mort",
    imageId: 49,
    titre: "Veille Concurrentielle IA",
    descriptionCourte: "Prix, offres, avis, mentions — rapport quotidien auto",
    descriptionLongue: `Veille concurrentielle automatisée par IA. Surveillance prix, offres, avis, mentions sur le web. Rapport quotidien.`,
    outils: ["n8n", "OpenAI", "Apify", "Google Sheets"],
    secteurs: ["marketing", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 4,
        description: "1 concurrent",
        features: ["1 concurrent", "Rapport hebdo"],
        workflows: ["Scraping → Rapport hebdo"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1400,
        delaiJours: 6,
        description: "5 concurrents",
        features: ["5 concurrents", "Alertes temps réel", "Dashboard"],
        workflows: ["Multi-scraping → IA → Alertes → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2800,
        delaiJours: 8,
        description: "Concurrents illimités",
        features: ["Concurrents illimités", "IA analyse", "API veille"],
        workflows: ["Scraping illimité", "IA analyse", "API veille"],
        livrables: ["API veille", "Dashboard complet"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 50,
    slug: "logistique-suivi-facturation",
    categorie: "angle-mort",
    imageId: 50,
    titre: "Logistique — Suivi & Facturation",
    descriptionCourte: "Colis, livreur, POD, facturation à la livraison — auto",
    descriptionLongue: `Solution logistique complète : suivi colis, gestion livreur, POD électronique, facturation déclenchée à la livraison.`,
    outils: ["n8n", "Shipstation", "Stripe", "Twilio"],
    secteurs: ["logistique", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 5,
        description: "Suivi colis",
        features: ["Suivi colis", "Notif client"],
        workflows: ["Suivi → Notification client"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 7,
        description: "Multi-transporteurs",
        features: ["Multi-transporteurs", "POD auto", "Facturation"],
        workflows: ["Multi-transporteurs → POD → Facturation"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 10,
        description: "Flotte complète",
        features: [
          "Flotte complète",
          "Optimisation tournées",
          "Dashboard logistique",
        ],
        workflows: ["Flotte complète", "Optimisation IA", "Dashboard"],
        livrables: ["Système complet", "Dashboard logistique"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 51,
    slug: "lead-scoring-ia",
    categorie: "angle-mort",
    imageId: 51,
    titre: "Lead Scoring IA Automatique",
    descriptionCourte:
      "Comportement → score IA → prioritisation équipe commerciale",
    descriptionLongue: `Score automatique des leads basé sur leur comportement. Priorisation de l'équipe commerciale.`,
    outils: ["n8n", "OpenAI", "HubSpot", "Slack"],
    secteurs: ["ventes", "marketing"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 800,
        delaiJours: 4,
        description: "Score simple",
        features: ["Score simple", "CRM sync"],
        workflows: ["Score → CRM sync"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1800,
        delaiJours: 6,
        description: "Multi-critères",
        features: ["Multi-critères", "IA avancée", "Alertes chaud"],
        workflows: ["Multi-critères → IA Scoring → Alertes"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3500,
        delaiJours: 8,
        description: "Prédiction conversion",
        features: ["Prédiction conversion", "Dashboard vente", "API scoring"],
        workflows: ["Prédiction IA", "API scoring", "Dashboard vente"],
        livrables: ["API scoring", "Dashboard vente"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 52,
    slug: "rh-onboarding-employe",
    categorie: "angle-mort",
    imageId: 52,
    titre: "RH — Onboarding Employé",
    descriptionCourte:
      "Embauche → accès → formation → congés → offboarding auto",
    descriptionLongue: `Parcours employé automatisé : onboarding, création accès, formation, gestion congés, offboarding.`,
    outils: ["Make", "Slack", "Notion", "Google Workspace"],
    secteurs: ["rh", "entreprise"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 700,
        delaiJours: 5,
        description: "Embauche → accès",
        features: ["Embauche → accès", "Email bienvenue"],
        workflows: ["Embauche → Création accès → Email"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 7,
        description: "Parcours complet",
        features: ["Parcours complet", "Formation auto", "Congés"],
        workflows: ["Onboarding complet", "Formation", "Congés"],
        livrables: ["3 workflows", "Dashboard RH"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 10,
        description: "Plateforme RH",
        features: ["Plateforme RH", "Évaluations", "Analytics talent"],
        workflows: ["Plateforme RH complète", "Évaluations", "Analytics"],
        livrables: ["Portail RH", "Dashboard analytics"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 53,
    slug: "agriculture-alertes",
    categorie: "angle-mort",
    imageId: 53,
    titre: "Agriculture — Alertes & Commandes",
    descriptionCourte: "Météo, irrigation, commandes, rapports récolte — auto",
    descriptionLongue: `Solutions agricoles : alertes météo, pilotage irrigation, gestion commandes, rapports récolte automatisés.`,
    outils: ["n8n", "OpenWeather", "Twilio"],
    secteurs: ["agriculture"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 4,
        description: "Alertes météo",
        features: ["Alertes météo", "SMS commande"],
        workflows: ["Météo → Alerte SMS"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 6,
        description: "Irrigation auto",
        features: ["Irrigation auto", "Dashboard récolte", "Prévisions"],
        workflows: ["Météo → Irrigation → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 8,
        description: "Ferme connectée",
        features: ["Ferme connectée", "IA prédictive", "Marketplace"],
        workflows: ["Ferme connectée", "IA prédictions", "Marketplace"],
        livrables: ["Système complet", "Dashboard agricole"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 54,
    slug: "referral-parrainage",
    categorie: "angle-mort",
    imageId: 54,
    titre: "Referral & Parrainage Automatisé",
    descriptionCourte:
      "Parrainage → suivi → récompense → rapport conversion auto",
    descriptionLongue: `Programme de parrainage automatisé. Suivi des filleuls, attribution récompenses, rapports conversion.`,
    outils: ["Make", "Stripe", "Mailgun", "Airtable"],
    secteurs: ["saas", "ecommerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 3,
        description: "Lien parrainage",
        features: ["Lien parrainage", "Email bienvenue"],
        workflows: ["Parrainage → Email bienvenue"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 5,
        description: "Suivi conversion",
        features: ["Suivi conversion", "Récompense auto", "Dashboard"],
        workflows: ["Parrainage → Suivi → Récompense → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 7,
        description: "Multi-niveaux",
        features: ["Multi-niveaux", "IA optimisation", "API partenaire"],
        workflows: ["Multi-niveaux", "IA optimisation", "API"],
        livrables: ["API partenaire", "Dashboard complet"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 55,
    slug: "migration-nettoyage",
    categorie: "angle-mort",
    imageId: 55,
    titre: "Migration & Nettoyage Workflows",
    descriptionCourte: "Reprise workflows cassés Make/Zapier — audit + rebuild",
    descriptionLongue: `Audit et migration de vos workflows existants (Make, Zapier). Reconstruction propre, documentation, transfert.`,
    outils: ["Make", "n8n", "Zapier"],
    secteurs: ["tous"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        description: "Audit + 1 workflow",
        features: ["Audit", "1 workflow migré"],
        workflows: ["Audit → Migration 1 workflow"],
        livrables: ["Rapport audit", "Workflow migré"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Standard",
        prix: 800,
        delaiJours: 5,
        description: "5 workflows",
        features: ["5 workflows", "Documentation", "Tests"],
        workflows: ["Audit → Migration 5 workflows → Tests"],
        livrables: ["5 workflows migrés", "Documentation"],
        supportJours: 21,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 7,
        description: "Migration complète",
        features: ["Migration complète", "Optimisation", "Formation"],
        workflows: ["Migration complète", "Optimisation", "Formation"],
        livrables: ["Système optimisé", "Formation équipe"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 56,
    slug: "evenementiel-inscriptions",
    categorie: "angle-mort",
    imageId: 56,
    titre: "Événementiel — Gestion Inscriptions",
    descriptionCourte: "Inscrip. → badge → rappel → feedback → certificat auto",
    descriptionLongue: `Solution événementielle : inscriptions, génération badges, rappels, feedback post-événement, certificats.`,
    outils: ["Make", "Tito", "Canva API", "Mailgun"],
    secteurs: ["event", "conference"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 450,
        delaiJours: 3,
        description: "Inscriptions",
        features: ["Inscriptions", "Email rappel"],
        workflows: ["Inscription → Email rappel"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 5,
        description: "Badge + feedback",
        features: ["Badge PDF", "Feedback auto", "Certificat"],
        workflows: ["Inscription → Badge → Feedback → Certificat"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 7,
        description: "Check-in + app",
        features: ["Check-in QR code", "Mobile app", "Analytics event"],
        workflows: ["Check-in QR code", "App mobile", "Analytics"],
        livrables: ["Application mobile", "Dashboard analytics"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 57,
    slug: "syndic-copropriete",
    categorie: "angle-mort",
    imageId: 57,
    titre: "Syndic / Copropriété — Gestion Auto",
    descriptionCourte:
      "AG, charges, travaux, comms copropriétaires — automatisés",
    descriptionLongue: `Solution pour syndics : gestion AG, appels de charges, suivi travaux, communications copropriétaires.`,
    outils: ["Make", "WhatsApp", "Stripe", "Google Drive"],
    secteurs: ["immobilier", "syndic"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 4,
        description: "Appels charges",
        features: ["Appels charges", "Email copros"],
        workflows: ["Appels charges → Email"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1400,
        delaiJours: 6,
        description: "AG digitale",
        features: ["AG digitale", "Suivi travaux", "Dashboard"],
        workflows: ["AG digitale", "Suivi travaux", "Dashboard"],
        livrables: ["3 workflows", "Dashboard syndic"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2800,
        delaiJours: 10,
        description: "Portail copro",
        features: ["Portail copro", "Paiement CB", "Maintenance prédictive"],
        workflows: ["Portail copro", "Paiement en ligne", "Maintenance IA"],
        livrables: ["Portail copro", "Dashboard maintenance"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 58,
    slug: "newsletter-ia",
    categorie: "angle-mort",
    imageId: 58,
    titre: "Newsletter IA Personnalisée",
    descriptionCourte:
      "Contenu IA selon profil lecteur, envoi segmenté, stats auto",
    descriptionLongue: `Newsletter générée par IA, personnalisée selon les préférences lecteur. Segmentation automatique, stats détaillées.`,
    outils: ["n8n", "OpenAI", "ConvertKit", "Supabase"],
    secteurs: ["marketing", "media"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 4,
        description: "Génération contenu",
        features: ["Génération contenu", "Envoi segmenté"],
        workflows: ["IA génération → Envoi segmenté"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 6,
        description: "Personnalisation",
        features: ["Personnalisation", "A/B testing", "Dashboard stats"],
        workflows: ["Contenu IA → Personnalisation → A/B test → Dashboard"],
        livrables: ["3 workflows", "Dashboard stats"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 8,
        description: "Multi-nl + fine-tuning",
        features: ["Multi-nl", "IA fine-tuning", "Monétisation auto"],
        workflows: ["Multi-newsletters", "IA fine-tuning", "Monétisation"],
        livrables: ["Système complet", "API newsletter"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 59,
    slug: "veille-appels-offres-ia",
    categorie: "angle-mort",
    imageId: 59,
    titre: "Veille Appels d'Offres IA",
    descriptionCourte: "Marchés publics → scoring IA → alerte équipe — auto",
    descriptionLongue: `Veille automatisée des appels d'offres. Scraping, scoring par IA, alertes équipe commerciale.`,
    outils: ["n8n", "OpenAI", "Slack", "Airtable"],
    secteurs: ["b2b", "public"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 700,
        delaiJours: 5,
        description: "1 source",
        features: ["1 source", "Alerte email"],
        workflows: ["Scraping → Alerte email"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 7,
        description: "3 sources",
        features: ["3 sources", "Scoring IA", "Dashboard"],
        workflows: ["Multi-sources → Scoring IA → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 10,
        description: "Sources illimitées",
        features: ["Sources illimitées", "Réponse IA", "API veille"],
        workflows: ["Scraping illimité", "IA analyse", "API veille"],
        livrables: ["API veille", "Dashboard complet"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 60,
    slug: "reputation-avis",
    categorie: "angle-mort",
    imageId: 60,
    titre: "Réputation — Avis Multi-Plateforme",
    descriptionCourte:
      "Post-achat → Google/Trustpilot → modération IA → réponse",
    descriptionLongue: `Gestion automatisée des avis clients. Demande post-achat, modération IA, réponses automatiques.`,
    outils: ["Make", "OpenAI", "Google Reviews API", "Trustpilot API"],
    secteurs: ["ecommerce", "service"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 3,
        description: "Demande avis",
        features: ["Demande avis email", "Réponse auto"],
        workflows: ["Post-achat → Demande avis → Réponse auto"],
        livrables: ["Workflow configuré"],
        supportJours: 14,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 5,
        description: "Multi-plateformes",
        features: ["Multi-plateformes", "Modération IA", "Dashboard"],
        workflows: ["Multi-plateformes → Modération IA → Dashboard"],
        livrables: ["3 workflows", "Dashboard modération"],
        supportJours: 21,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 7,
        description: "IA avancée",
        features: ["IA avancée", "Curation avis", "API réputation"],
        workflows: ["IA avancée", "Curation", "API réputation"],
        livrables: ["API réputation", "Dashboard complet"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
];
