// lib/offres/niches.ts
import type { OffreComplet } from "./type";

export const nichesOffres: OffreComplet[] = [
  {
    id: 21,
    slug: "immobilier-lead-qualification",
    categorie: "niche",
    imageId: 21,
    titre: "Immobilier — Lead Qualification",
    descriptionCourte:
      "Leads entrants → WhatsApp auto → CRM → agenda commercial",
    descriptionLongue: `Spécialement conçu pour les agents immobiliers. Qualifiez automatiquement vos leads entrants, envoyez des informations par WhatsApp, synchronisez votre CRM, et prenez RDV automatiquement.`,
    outils: ["Make", "WhatsApp Business", "HubSpot", "Calendly"],
    secteurs: ["immobilier", "promotion"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 5,
        features: ["WhatsApp auto", "CRM sync", "RDV basique"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 7,
        features: ["Lead scoring", "Agenda connecté", "Relances auto"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 10,
        features: [
          "Pipeline complet",
          "IA qualification",
          "Dashboard promoteur",
        ],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 22,
    slug: "agence-marketing-reporting",
    categorie: "niche",
    imageId: 22,
    titre: "Agence Marketing — Reporting Client",
    descriptionCourte: "Meta + Google Ads + SEO → rapport PDF envoyé auto",
    descriptionLongue: `Pour les agences : rapports clients automatisés. Agrégation des données Meta Ads, Google Ads, SEO, et envoi d'un rapport PDF personnalisé.`,
    outils: ["n8n", "Meta API", "Google Ads API", "Google Sheets"],
    secteurs: ["marketing", "agence"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 4,
        features: ["2 sources", "PDF simple"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 900,
        delaiJours: 6,
        features: ["5 sources", "Template personnalisé", "Multi-clients"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1800,
        delaiJours: 8,
        features: ["Sources illimitées", "White-label", "Dashboard interactif"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 23,
    slug: "coach-systeme-complet",
    categorie: "niche",
    imageId: 23,
    titre: "Coach & Consultant — Système Complet",
    descriptionCourte:
      "Booking → onboarding → ressources → facture — tout auto",
    descriptionLongue: `Système tout-en-un pour coachs et consultants. Prise de RDV, onboarding client, accès ressources, facturation, relances — 100% automatisé.`,
    outils: ["Make", "Calendly", "Stripe", "Notion"],
    secteurs: ["coaching", "consulting"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 450,
        delaiJours: 4,
        features: ["Booking", "Email onboarding"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 6,
        features: ["Booking + facture", "Accès ressources", "Relances"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 10,
        features: ["Système complet", "CRM client", "Programme fidélité"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 24,
    slug: "saas-trial-to-paid",
    categorie: "niche",
    imageId: 24,
    titre: "SaaS — Trial to Paid Automation",
    descriptionCourte:
      "Activation, drip emails, score engagement, alerte churn",
    descriptionLongue: `Maximisez vos conversions d'essai vers payant. Email nurturing, scoring d'engagement, alertes churn, auto-upgrade.`,
    outils: ["n8n", "OpenAI", "HubSpot", "Stripe"],
    secteurs: ["saas", "tech"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 5,
        features: ["Drip emails", "Alertes basiques"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 8,
        features: ["Scoring IA", "Auto-upgrade", "Dashboard churn"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 12,
        features: [
          "Prédiction conversion",
          "Segmentation avancée",
          "A/B testing",
        ],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 25,
    slug: "cabinet-comptable",
    categorie: "niche",
    imageId: 25,
    titre: "Cabinet Comptable — Relances & Rapports",
    descriptionCourte: "Relances impayés, rapports mensuels clients, sync ERP",
    descriptionLongue: `Solution complète pour cabinets comptables. Relances automatiques des impayés, rapports mensuels clients, synchronisation ERP.`,
    outils: ["Make", "QuickBooks", "Slack", "Google Sheets"],
    secteurs: ["comptabilite", "finance"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 4,
        features: ["Relances email", "Rapport simple"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 6,
        features: ["Multi-niveaux relance", "Sync ERP", "Dashboard client"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 10,
        features: [
          "Automatisation complète",
          "Portail client",
          "Analyse prédictive",
        ],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 26,
    slug: "youtube-pipeline-ia",
    categorie: "niche",
    imageId: 26,
    titre: "YouTube — Pipeline Contenu IA",
    descriptionCourte:
      "Idée → script IA → publication → stats → newsletter auto",
    descriptionLongue: `Chaîne YouTube automatisée : génération d'idées, script par IA, publication programmée, récupération stats, envoi newsletter.`,
    outils: ["n8n", "OpenAI", "YouTube API", "ConvertKit"],
    secteurs: ["content", "video"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 5,
        features: ["Génération script", "Publication manuelle"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 7,
        features: ["Script + thumbnail IA", "Programmation", "Stats auto"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 10,
        features: ["Pipeline complet", "Multi-chaînes", "Newsletter intégrée"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 27,
    slug: "restaurant-reservations",
    categorie: "niche",
    imageId: 27,
    titre: "Restaurant — Réservations & Avis",
    descriptionCourte: "Résa → rappel WhatsApp → avis Google → commande auto",
    descriptionLongue: `Solution tout-en-un pour restaurants. Prise de réservation, rappel confirmation, demande d'avis automatique après visite.`,
    outils: ["Make", "WhatsApp", "Google Reviews API"],
    secteurs: ["restauration", "hotellerie"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 3,
        features: ["Booking simple", "Rappel WhatsApp"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 800,
        delaiJours: 5,
        features: ["Multi-salles", "Demande avis auto", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1500,
        delaiJours: 7,
        features: [
          "Commande en ligne",
          "Programme fidélité",
          "Analytics avancé",
        ],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 28,
    slug: "ecommerce-panier-abandonne",
    categorie: "niche",
    imageId: 28,
    titre: "E-commerce — Panier Abandonné",
    descriptionCourte: "Email + WhatsApp + SMS — récupération séquencée auto",
    descriptionLongue: `Récupérez vos paniers abandonnés avec une séquence multi-canaux : email, WhatsApp, SMS. Configurable et dashboard de performance.`,
    outils: ["Make", "Shopify", "Twilio", "Brevo"],
    secteurs: ["ecommerce", "retail"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 3,
        features: ["Email séquence", "Remise auto"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 900,
        delaiJours: 5,
        features: ["Email + SMS", "A/B testing", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1800,
        delaiJours: 7,
        features: ["Multi-canaux", "IA personnalisation", "Prédiction churn"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 29,
    slug: "agence-recrutement-ia",
    categorie: "niche",
    imageId: 29,
    titre: "Agence Recrutement — Pipeline IA",
    descriptionCourte: "CV → scoring IA → notif client → contrat → onboarding",
    descriptionLongue: `Pipeline complet pour agences de recrutement. Parsing CV, scoring par IA, notification client, génération contrat, onboarding candidat.`,
    outils: ["n8n", "OpenAI", "DocuSign", "Slack"],
    secteurs: ["recrutement", "rh"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 5,
        features: ["Parsing CV", "Scoring simple"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 8,
        features: ["CV + scoring IA", "Portail client", "Contrat auto"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 12,
        features: ["Pipeline complet", "Matching IA", "Dashboard recrutement"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 30,
    slug: "sante-rappels",
    categorie: "niche",
    imageId: 30,
    titre: "Santé — Rappels & Formulaires",
    descriptionCourte: "RDV → rappel WhatsApp → formulaire → suivi post-visite",
    descriptionLongue: `Pour professionnels de santé : prise RDV, rappels WhatsApp, formulaires pré-consultation, suivi post-visite automatisé.`,
    outils: ["Make", "WhatsApp", "Typeform", "Doctolib"],
    secteurs: ["sante", "medical"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 450,
        delaiJours: 4,
        features: ["Rappels SMS", "Formulaire simple"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 6,
        features: ["Multi-canaux", "Pré-consultation", "Suivi auto"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 8,
        features: ["Dossier patient", "Télémédecine", "Analytics santé"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 31,
    slug: "formation-lms",
    categorie: "niche",
    imageId: 31,
    titre: "Formation en Ligne — LMS Automation",
    descriptionCourte:
      "Inscription → accès → progression → certificat → upsell",
    descriptionLongue: `Automatisez votre plateforme de formation : inscription, accès aux cours, suivi progression, génération certificat, upsell.`,
    outils: ["n8n", "Teachable", "Stripe", "Zapier"],
    secteurs: ["education", "formation"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 4,
        features: ["Inscription auto", "Accès LMS"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 6,
        features: ["Suivi progression", "Certificat auto", "Email nurturing"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 10,
        features: ["LMS complet", "Communauté", "Affiliation auto"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 32,
    slug: "agence-pub-leads",
    categorie: "niche",
    imageId: 32,
    titre: "Agence Pub — Gestion Leads Entrants",
    descriptionCourte: "Leads Meta/Google → qualif auto → assignation → CRM",
    descriptionLongue: `Capture automatique des leads Meta/Google Ads, qualification, assignation à l'équipe commerciale, injection CRM.`,
    outils: ["Make", "Meta Ads", "Google Ads", "HubSpot"],
    secteurs: ["marketing", "advertising"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 3,
        features: ["Capture leads", "CRM sync"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 900,
        delaiJours: 5,
        features: ["Qualification auto", "Assignation équipe", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1800,
        delaiJours: 7,
        features: ["Scoring IA", "Budget tracking", "Multi-comptes"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 33,
    slug: "hotellerie-guest",
    categorie: "niche",
    imageId: 33,
    titre: "Hôtellerie — Guest Journey Auto",
    descriptionCourte: "Résa → pré-séjour → upsell → post-avis Google auto",
    descriptionLongue: `Parcours client automatisé pour hôtels : confirmation, emails pré-séjour, offres d'upsell, demande d'avis post-séjour.`,
    outils: ["Make", "WhatsApp", "Google Reviews", "Stripe"],
    secteurs: ["hotellerie", "tourisme"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 3,
        features: ["Confirmation", "Email pré-séjour"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 900,
        delaiJours: 5,
        features: ["Upsell auto", "Demande avis", "Dashboard taux occupation"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1800,
        delaiJours: 7,
        features: [
          "Programme fidélité",
          "IA recommandation",
          "Multi-propriétés",
        ],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 34,
    slug: "seo-veille-reporting",
    categorie: "niche",
    imageId: 34,
    titre: "SEO — Veille & Reporting Auto",
    descriptionCourte:
      "Positions, alertes, rapports, veille concurrents — auto",
    descriptionLongue: `Solution SEO complète : suivi positions, alertes changements, rapports hebdomadaires, veille concurrentielle automatisée.`,
    outils: ["n8n", "SEMrush API", "Google Search Console", "Slack"],
    secteurs: ["seo", "marketing"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 3,
        features: ["Suivi positions", "Rapport hebdo"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 800,
        delaiJours: 5,
        features: ["Alertes en temps réel", "Veille concurrents", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1500,
        delaiJours: 7,
        features: ["Prédiction trafic", "Backlink monitoring", "Stratégie IA"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 35,
    slug: "studio-creatif",
    categorie: "niche",
    imageId: 35,
    titre: "Studio Créatif — Devis & Livraison",
    descriptionCourte: "Contact → devis → booking → livraison → avis auto",
    descriptionLongue: `Pour studios créatifs : automatisation du cycle client complet. Devis, validation, planning, livraison fichiers, demande d'avis.`,
    outils: ["Make", "PandaDoc", "Calendly", "Google Drive"],
    secteurs: ["creatif", "design"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 3,
        features: ["Devis auto", "Email validation"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 800,
        delaiJours: 5,
        features: ["Signature incluse", "Planning auto", "Livraison Drive"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1500,
        delaiJours: 7,
        features: ["Workflow complet", "Portail client", "Facturation"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 36,
    slug: "promoteur-immobilier",
    categorie: "niche",
    imageId: 36,
    titre: "Promoteur Immobilier — Suivi Projet",
    descriptionCourte: "Prospects → avancement → docs → closing automatisé",
    descriptionLongue: `Pour promoteurs immobiliers : suivi automatique des prospects, gestion documentaire, relances, closing.`,
    outils: ["n8n", "HubSpot", "DocuSign", "WhatsApp"],
    secteurs: ["immobilier", "promotion"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 700,
        delaiJours: 5,
        features: ["Suivi prospects", "Docs basiques"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 8,
        features: ["Pipeline vente", "Signature digitale", "Relances auto"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 12,
        features: [
          "Plateforme promoteur",
          "Gestion chantier",
          "Dashboard investisseur",
        ],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 37,
    slug: "agence-creative-projets",
    categorie: "niche",
    imageId: 37,
    titre: "Agence Créative — Gestion Projets",
    descriptionCourte:
      "Brief → tâches → livraison → facture → avis — tout auto",
    descriptionLongue: `Pour agences créatives : automatisation complète du flux projet. Brief client, création tâches, livraison, facturation, demande avis.`,
    outils: ["Make", "ClickUp", "Stripe", "Slack"],
    secteurs: ["agence", "creatif"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 4,
        features: ["Brief → tâches", "Email client"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 6,
        features: ["Brief + livraison", "Facture auto", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 8,
        features: ["Workflow complet", "Portail client", "Analytics projet"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 38,
    slug: "association-gestion",
    categorie: "niche",
    imageId: 38,
    titre: "Association — Gestion Adhérents",
    descriptionCourte:
      "Adhésions, relances, newsletters, rapports financiers auto",
    descriptionLongue: `Solution pour associations : gestion adhérents, renouvellements, communication, rapports financiers automatisés.`,
    outils: ["Make", "Mailchimp", "Stripe", "Google Sheets"],
    secteurs: ["association", "nonprofit"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        features: ["Adhésions", "Email bienvenue"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 700,
        delaiJours: 5,
        features: ["Renouvellements", "Newsletter", "Rapports basiques"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1400,
        delaiJours: 7,
        features: ["Portail adhérent", "Paiement CB", "Dashboard complet"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 39,
    slug: "commerce-local-fidelite",
    categorie: "niche",
    imageId: 39,
    titre: "Commerce Local — Fidélité & Avis",
    descriptionCourte: "Programme fidélité, SMS anniversaire, avis Google auto",
    descriptionLongue: `Pour commerces locaux : programme fidélité automatisé, SMS anniversaire, demande d'avis post-achat.`,
    outils: ["Make", "WhatsApp", "Google Reviews", "Stripe"],
    secteurs: ["retail", "commerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        features: ["Points fidélité", "Email anniversaire"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 700,
        delaiJours: 5,
        features: ["Carte fidélité", "SMS anniversaire", "Demande avis"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1400,
        delaiJours: 7,
        features: ["Programme complet", "CRM local", "Analytics client"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 40,
    slug: "startup-ops-stack",
    categorie: "niche",
    imageId: 40,
    titre: "Startup — Ops Stack Connecté",
    descriptionCourte: "Notion + Slack + Linear + CRM + email — tout en 1 flux",
    descriptionLongue: `Stack opérationnelle complète pour startup. Connectez Notion, Slack, Linear, CRM, emails — tout automatisé.`,
    outils: ["n8n", "Notion", "Slack", "Linear", "HubSpot"],
    secteurs: ["startup", "tech"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 800,
        delaiJours: 5,
        features: ["3 outils connectés", "Sync basique"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1800,
        delaiJours: 8,
        features: ["5 outils", "Workflows automatisés", "Dashboard ops"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3500,
        delaiJours: 12,
        features: ["Stack complet", "Automatisation IA", "Scale ready"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
];
