// lib/offres/niches.ts
import type { OffreComplet } from "./types";

export const nichesOffres: OffreComplet[] = [
  {
    id: 21,
    slug: "immobilier-lead-qualification",
    categorie: "niche",
    imageId: 21,
    titre: "Immobilier — Lead Qualification",
    descriptionCourte:
      "Leads entrants → WhatsApp auto → CRM → agenda commercial",
    descriptionLongue: `Spécialement conçu pour les agents immobiliers. Qualifiez automatiquement vos leads entrants, envoyez des informations par WhatsApp, synchronisez votre CRM, et prenez RDV automatiquement.`,
    outils: ["Make", "WhatsApp Business", "HubSpot", "Calendly"],
    secteurs: ["immobilier", "promotion"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 5,
        description: "WhatsApp + CRM basique",
        features: ["WhatsApp auto", "CRM sync", "RDV basique"],
        workflows: ["Lead → WhatsApp → CRM"],
        livrables: ["Workflow configuré", "Doc PDF"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 7,
        description: "Lead scoring + agenda",
        features: ["Lead scoring", "Agenda connecté", "Relances auto"],
        workflows: ["Lead → Scoring → Agenda → Relances"],
        livrables: ["3 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 10,
        description: "Pipeline complet IA",
        features: [
          "Pipeline complet",
          "IA qualification",
          "Dashboard promoteur",
        ],
        workflows: ["Pipeline complet", "IA qualification", "Dashboard"],
        livrables: ["Système complet", "Formation", "Dashboard"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 22,
    slug: "agence-marketing-reporting",
    categorie: "niche",
    imageId: 22,
    titre: "Agence Marketing — Reporting Client",
    descriptionCourte: "Meta + Google Ads + SEO → rapport PDF envoyé auto",
    descriptionLongue: `Pour les agences : rapports clients automatisés. Agrégation des données Meta Ads, Google Ads, SEO, et envoi d'un rapport PDF personnalisé.`,
    outils: ["n8n", "Meta API", "Google Ads API", "Google Sheets"],
    secteurs: ["marketing", "agence"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 4,
        description: "2 sources",
        features: ["2 sources", "PDF simple"],
        workflows: ["2 sources → PDF"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 900,
        delaiJours: 6,
        description: "5 sources",
        features: ["5 sources", "Template personnalisé", "Multi-clients"],
        workflows: ["5 sources → Template → Multi-clients"],
        livrables: ["3 workflows", "Doc PDF"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1800,
        delaiJours: 8,
        description: "Sources illimitées",
        features: ["Sources illimitées", "White-label", "Dashboard interactif"],
        workflows: ["Sources illimitées → Dashboard → API"],
        livrables: ["Système complet", "Dashboard", "API"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 23,
    slug: "coach-systeme-complet",
    categorie: "niche",
    imageId: 23,
    titre: "Coach & Consultant — Système Complet",
    descriptionCourte:
      "Booking → onboarding → ressources → facture — tout auto",
    descriptionLongue: `Système tout-en-un pour coachs et consultants. Prise de RDV, onboarding client, accès ressources, facturation, relances — 100% automatisé.`,
    outils: ["Make", "Calendly", "Stripe", "Notion"],
    secteurs: ["coaching", "consulting"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 450,
        delaiJours: 4,
        description: "Booking + email",
        features: ["Booking", "Email onboarding"],
        workflows: ["Booking → Email onboarding"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 6,
        description: "Booking + facture + ressources",
        features: ["Booking + facture", "Accès ressources", "Relances"],
        workflows: ["Booking → Facture → Accès ressources → Relances"],
        livrables: ["3 workflows", "Doc + vidéo"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 10,
        description: "Système complet",
        features: ["Système complet", "CRM client", "Programme fidélité"],
        workflows: ["Système complet", "CRM", "Fidélité"],
        livrables: ["Système complet", "Formation", "Dashboard"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 24,
    slug: "saas-trial-to-paid",
    categorie: "niche",
    imageId: 24,
    titre: "SaaS — Trial to Paid Automation",
    descriptionCourte:
      "Activation, drip emails, score engagement, alerte churn",
    descriptionLongue: `Maximisez vos conversions d'essai vers payant. Email nurturing, scoring d'engagement, alertes churn, auto-upgrade.`,
    outils: ["n8n", "OpenAI", "HubSpot", "Stripe"],
    secteurs: ["saas", "tech"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 5,
        description: "Drip emails",
        features: ["Drip emails", "Alertes basiques"],
        workflows: ["Trial → Drip emails → Alertes"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 8,
        description: "Scoring IA",
        features: ["Scoring IA", "Auto-upgrade", "Dashboard churn"],
        workflows: ["Trial → Scoring IA → Auto-upgrade → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 12,
        description: "Prédiction conversion",
        features: [
          "Prédiction conversion",
          "Segmentation avancée",
          "A/B testing",
        ],
        workflows: ["Prédiction IA", "Segmentation", "A/B testing"],
        livrables: ["API scoring", "Dashboard complet"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 25,
    slug: "cabinet-comptable",
    categorie: "niche",
    imageId: 25,
    titre: "Cabinet Comptable — Relances & Rapports",
    descriptionCourte: "Relances impayés, rapports mensuels clients, sync ERP",
    descriptionLongue: `Solution complète pour cabinets comptables. Relances automatiques des impayés, rapports mensuels clients, synchronisation ERP.`,
    outils: ["Make", "QuickBooks", "Slack", "Google Sheets"],
    secteurs: ["comptabilite", "finance"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 4,
        description: "Relances email",
        features: ["Relances email", "Rapport simple"],
        workflows: ["Impayé → Relance email → Rapport"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 6,
        description: "Multi-niveaux relance",
        features: ["Multi-niveaux relance", "Sync ERP", "Dashboard client"],
        workflows: ["Impayé → Relances multi-niveaux → Sync ERP → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 10,
        description: "Automatisation complète",
        features: [
          "Automatisation complète",
          "Portail client",
          "Analyse prédictive",
        ],
        workflows: [
          "Comptabilité complète",
          "Portail client",
          "Prédictions IA",
        ],
        livrables: ["Système complet", "Portail client"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 26,
    slug: "youtube-pipeline-ia",
    categorie: "niche",
    imageId: 26,
    titre: "YouTube — Pipeline Contenu IA",
    descriptionCourte:
      "Idée → script IA → publication → stats → newsletter auto",
    descriptionLongue: `Chaîne YouTube automatisée : génération d'idées, script par IA, publication programmée, récupération stats, envoi newsletter.`,
    outils: ["n8n", "OpenAI", "YouTube API", "ConvertKit"],
    secteurs: ["content", "video"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 5,
        description: "Script IA",
        features: ["Génération script", "Publication manuelle"],
        workflows: ["Idée → Script IA → Publication manuelle"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 7,
        description: "Script + thumbnail",
        features: ["Script + thumbnail IA", "Programmation", "Stats auto"],
        workflows: ["Idée → Script + Thumbnail IA → Programmation → Stats"],
        livrables: ["3 workflows", "Dashboard stats"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 10,
        description: "Pipeline complet",
        features: ["Pipeline complet", "Multi-chaînes", "Newsletter intégrée"],
        workflows: ["Pipeline complet YouTube", "Multi-chaînes", "Newsletter"],
        livrables: ["Système complet", "Formation"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 27,
    slug: "restaurant-reservations",
    categorie: "niche",
    imageId: 27,
    titre: "Restaurant — Réservations & Avis",
    descriptionCourte: "Résa → rappel WhatsApp → avis Google → commande auto",
    descriptionLongue: `Solution tout-en-un pour restaurants. Prise de réservation, rappel confirmation, demande d'avis automatique après visite.`,
    outils: ["Make", "WhatsApp", "Google Reviews API"],
    secteurs: ["restauration", "hotellerie"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 3,
        description: "Booking + rappel",
        features: ["Booking simple", "Rappel WhatsApp"],
        workflows: ["Réservation → Rappel WhatsApp"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 800,
        delaiJours: 5,
        description: "Multi-salles + avis",
        features: ["Multi-salles", "Demande avis auto", "Dashboard"],
        workflows: ["Réservation → Rappel → Avis → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1500,
        delaiJours: 7,
        description: "Commande en ligne",
        features: [
          "Commande en ligne",
          "Programme fidélité",
          "Analytics avancé",
        ],
        workflows: ["Commande en ligne", "Fidélité", "Analytics"],
        livrables: ["Système complet", "Application fidélité"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 28,
    slug: "ecommerce-panier-abandonne",
    categorie: "niche",
    imageId: 28,
    titre: "E-commerce — Panier Abandonné",
    descriptionCourte: "Email + WhatsApp + SMS — récupération séquencée auto",
    descriptionLongue: `Récupérez vos paniers abandonnés avec une séquence multi-canaux : email, WhatsApp, SMS. Configurable et dashboard de performance.`,
    outils: ["Make", "Shopify", "Twilio", "Brevo"],
    secteurs: ["ecommerce", "retail"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 3,
        description: "Email séquence",
        features: ["Email séquence", "Remise auto"],
        workflows: ["Panier abandonné → Email séquence → Remise"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 900,
        delaiJours: 5,
        description: "Email + SMS",
        features: ["Email + SMS", "A/B testing", "Dashboard"],
        workflows: ["Panier → Email + SMS → A/B test → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1800,
        delaiJours: 7,
        description: "Multi-canaux + IA",
        features: ["Multi-canaux", "IA personnalisation", "Prédiction churn"],
        workflows: ["Multi-canaux", "IA personnalisation", "Prédiction"],
        livrables: ["Système complet", "API recommandation"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 29,
    slug: "agence-recrutement-ia",
    categorie: "niche",
    imageId: 29,
    titre: "Agence Recrutement — Pipeline IA",
    descriptionCourte: "CV → scoring IA → notif client → contrat → onboarding",
    descriptionLongue: `Pipeline complet pour agences de recrutement. Parsing CV, scoring par IA, notification client, génération contrat, onboarding candidat.`,
    outils: ["n8n", "OpenAI", "DocuSign", "Slack"],
    secteurs: ["recrutement", "rh"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 600,
        delaiJours: 5,
        description: "Parsing CV",
        features: ["Parsing CV", "Scoring simple"],
        workflows: ["CV → Parsing → Scoring simple"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 8,
        description: "CV + scoring IA",
        features: ["CV + scoring IA", "Portail client", "Contrat auto"],
        workflows: ["CV → Scoring IA → Portail client → Contrat"],
        livrables: ["3 workflows", "Portail client"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 12,
        description: "Pipeline complet IA",
        features: ["Pipeline complet", "Matching IA", "Dashboard recrutement"],
        workflows: ["Pipeline complet IA", "Matching IA", "Dashboard RH"],
        livrables: ["Système complet", "Dashboard recrutement"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 30,
    slug: "sante-rappels",
    categorie: "niche",
    imageId: 30,
    titre: "Santé — Rappels & Formulaires",
    descriptionCourte: "RDV → rappel WhatsApp → formulaire → suivi post-visite",
    descriptionLongue: `Pour professionnels de santé : prise RDV, rappels WhatsApp, formulaires pré-consultation, suivi post-visite automatisé.`,
    outils: ["Make", "WhatsApp", "Typeform", "Doctolib"],
    secteurs: ["sante", "medical"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 450,
        delaiJours: 4,
        description: "Rappels SMS",
        features: ["Rappels SMS", "Formulaire simple"],
        workflows: ["RDV → Rappel SMS → Formulaire"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 6,
        description: "Multi-canaux",
        features: ["Multi-canaux", "Pré-consultation", "Suivi auto"],
        workflows: ["RDV → Multi-canaux → Pré-consultation → Suivi"],
        livrables: ["3 workflows", "Dashboard patient"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 8,
        description: "Dossier patient",
        features: ["Dossier patient", "Télémédecine", "Analytics santé"],
        workflows: ["Dossier patient", "Télémédecine", "Analytics"],
        livrables: ["Système complet", "Portail patient"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 31,
    slug: "formation-lms",
    categorie: "niche",
    imageId: 31,
    titre: "Formation en Ligne — LMS Automation",
    descriptionCourte:
      "Inscription → accès → progression → certificat → upsell",
    descriptionLongue: `Automatisez votre plateforme de formation : inscription, accès aux cours, suivi progression, génération certificat, upsell.`,
    outils: ["n8n", "Teachable", "Stripe", "Zapier"],
    secteurs: ["education", "formation"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 500,
        delaiJours: 4,
        description: "Inscription + accès",
        features: ["Inscription auto", "Accès LMS"],
        workflows: ["Inscription → Accès LMS"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1200,
        delaiJours: 6,
        description: "Suivi + certificat",
        features: ["Suivi progression", "Certificat auto", "Email nurturing"],
        workflows: ["Progression → Certificat → Email nurturing"],
        livrables: ["3 workflows", "Dashboard formation"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2500,
        delaiJours: 10,
        description: "LMS complet",
        features: ["LMS complet", "Communauté", "Affiliation auto"],
        workflows: ["LMS complet", "Communauté", "Programme affiliation"],
        livrables: ["Système complet", "Communauté", "API"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 32,
    slug: "agence-pub-leads",
    categorie: "niche",
    imageId: 32,
    titre: "Agence Pub — Gestion Leads Entrants",
    descriptionCourte: "Leads Meta/Google → qualif auto → assignation → CRM",
    descriptionLongue: `Capture automatique des leads Meta/Google Ads, qualification, assignation à l'équipe commerciale, injection CRM.`,
    outils: ["Make", "Meta Ads", "Google Ads", "HubSpot"],
    secteurs: ["marketing", "advertising"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 3,
        description: "Capture leads",
        features: ["Capture leads", "CRM sync"],
        workflows: ["Leads → Capture → CRM sync"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 900,
        delaiJours: 5,
        description: "Qualification auto",
        features: ["Qualification auto", "Assignation équipe", "Dashboard"],
        workflows: ["Leads → Qualification → Assignation → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1800,
        delaiJours: 7,
        description: "Scoring IA",
        features: ["Scoring IA", "Budget tracking", "Multi-comptes"],
        workflows: ["Scoring IA", "Budget tracking", "Multi-comptes"],
        livrables: ["Système complet", "Dashboard pub"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 33,
    slug: "hotellerie-guest",
    categorie: "niche",
    imageId: 33,
    titre: "Hôtellerie — Guest Journey Auto",
    descriptionCourte: "Résa → pré-séjour → upsell → post-avis Google auto",
    descriptionLongue: `Parcours client automatisé pour hôtels : confirmation, emails pré-séjour, offres d'upsell, demande d'avis post-séjour.`,
    outils: ["Make", "WhatsApp", "Google Reviews", "Stripe"],
    secteurs: ["hotellerie", "tourisme"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 3,
        description: "Confirmation + email",
        features: ["Confirmation", "Email pré-séjour"],
        workflows: ["Réservation → Confirmation → Email pré-séjour"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 900,
        delaiJours: 5,
        description: "Upsell + avis",
        features: ["Upsell auto", "Demande avis", "Dashboard taux occupation"],
        workflows: ["Réservation → Upsell → Avis → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1800,
        delaiJours: 7,
        description: "Programme fidélité",
        features: [
          "Programme fidélité",
          "IA recommandation",
          "Multi-propriétés",
        ],
        workflows: ["Fidélité", "IA recommandation", "Multi-propriétés"],
        livrables: ["Système complet", "Programme fidélité"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 34,
    slug: "seo-veille-reporting",
    categorie: "niche",
    imageId: 34,
    titre: "SEO — Veille & Reporting Auto",
    descriptionCourte:
      "Positions, alertes, rapports, veille concurrents — auto",
    descriptionLongue: `Solution SEO complète : suivi positions, alertes changements, rapports hebdomadaires, veille concurrentielle automatisée.`,
    outils: ["n8n", "SEMrush API", "Google Search Console", "Slack"],
    secteurs: ["seo", "marketing"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 3,
        description: "Suivi positions",
        features: ["Suivi positions", "Rapport hebdo"],
        workflows: ["Positions → Rapport hebdo"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 800,
        delaiJours: 5,
        description: "Alertes temps réel",
        features: ["Alertes en temps réel", "Veille concurrents", "Dashboard"],
        workflows: ["Positions → Alertes → Veille → Dashboard"],
        livrables: ["3 workflows", "Dashboard SEO"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1500,
        delaiJours: 7,
        description: "Prédiction trafic",
        features: ["Prédiction trafic", "Backlink monitoring", "Stratégie IA"],
        workflows: ["Prédiction IA", "Backlinks", "Stratégie SEO"],
        livrables: ["Système complet", "API SEO"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 35,
    slug: "studio-creatif",
    categorie: "niche",
    imageId: 35,
    titre: "Studio Créatif — Devis & Livraison",
    descriptionCourte: "Contact → devis → booking → livraison → avis auto",
    descriptionLongue: `Pour studios créatifs : automatisation du cycle client complet. Devis, validation, planning, livraison fichiers, demande d'avis.`,
    outils: ["Make", "PandaDoc", "Calendly", "Google Drive"],
    secteurs: ["creatif", "design"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 350,
        delaiJours: 3,
        description: "Devis auto",
        features: ["Devis auto", "Email validation"],
        workflows: ["Contact → Devis → Email validation"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 800,
        delaiJours: 5,
        description: "Signature + planning",
        features: ["Signature incluse", "Planning auto", "Livraison Drive"],
        workflows: ["Devis → Signature → Planning → Livraison Drive"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1500,
        delaiJours: 7,
        description: "Workflow complet",
        features: ["Workflow complet", "Portail client", "Facturation"],
        workflows: [
          "Workflow complet créatif",
          "Portail client",
          "Facturation",
        ],
        livrables: ["Système complet", "Portail client"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 36,
    slug: "promoteur-immobilier",
    categorie: "niche",
    imageId: 36,
    titre: "Promoteur Immobilier — Suivi Projet",
    descriptionCourte: "Prospects → avancement → docs → closing automatisé",
    descriptionLongue: `Pour promoteurs immobiliers : suivi automatique des prospects, gestion documentaire, relances, closing.`,
    outils: ["n8n", "HubSpot", "DocuSign", "WhatsApp"],
    secteurs: ["immobilier", "promotion"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 700,
        delaiJours: 5,
        description: "Suivi prospects",
        features: ["Suivi prospects", "Docs basiques"],
        workflows: ["Prospects → Suivi → Docs"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1500,
        delaiJours: 8,
        description: "Pipeline vente",
        features: ["Pipeline vente", "Signature digitale", "Relances auto"],
        workflows: ["Pipeline vente → Signature → Relances"],
        livrables: ["3 workflows", "Dashboard promoteur"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3000,
        delaiJours: 12,
        description: "Plateforme promoteur",
        features: [
          "Plateforme promoteur",
          "Gestion chantier",
          "Dashboard investisseur",
        ],
        workflows: ["Plateforme promoteur", "Gestion chantier", "Dashboard"],
        livrables: ["Système complet", "Portail investisseur"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 37,
    slug: "agence-creative-projets",
    categorie: "niche",
    imageId: 37,
    titre: "Agence Créative — Gestion Projets",
    descriptionCourte:
      "Brief → tâches → livraison → facture → avis — tout auto",
    descriptionLongue: `Pour agences créatives : automatisation complète du flux projet. Brief client, création tâches, livraison, facturation, demande avis.`,
    outils: ["Make", "ClickUp", "Stripe", "Slack"],
    secteurs: ["agence", "creatif"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 400,
        delaiJours: 4,
        description: "Brief → tâches",
        features: ["Brief → tâches", "Email client"],
        workflows: ["Brief → Création tâches → Email client"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1000,
        delaiJours: 6,
        description: "Brief + livraison + facture",
        features: ["Brief + livraison", "Facture auto", "Dashboard"],
        workflows: ["Brief → Tâches → Livraison → Facture → Dashboard"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 2000,
        delaiJours: 8,
        description: "Workflow complet",
        features: ["Workflow complet", "Portail client", "Analytics projet"],
        workflows: ["Workflow complet agence", "Portail client", "Analytics"],
        livrables: ["Système complet", "Portail client"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 38,
    slug: "association-gestion",
    categorie: "niche",
    imageId: 38,
    titre: "Association — Gestion Adhérents",
    descriptionCourte:
      "Adhésions, relances, newsletters, rapports financiers auto",
    descriptionLongue: `Solution pour associations : gestion adhérents, renouvellements, communication, rapports financiers automatisés.`,
    outils: ["Make", "Mailchimp", "Stripe", "Google Sheets"],
    secteurs: ["association", "nonprofit"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        description: "Adhésions",
        features: ["Adhésions", "Email bienvenue"],
        workflows: ["Adhésion → Email bienvenue"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 700,
        delaiJours: 5,
        description: "Renouvellements + newsletter",
        features: ["Renouvellements", "Newsletter", "Rapports basiques"],
        workflows: ["Renouvellements → Newsletter → Rapports"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1400,
        delaiJours: 7,
        description: "Portail adhérent",
        features: ["Portail adhérent", "Paiement CB", "Dashboard complet"],
        workflows: ["Portail adhérent", "Paiement en ligne", "Dashboard"],
        livrables: ["Système complet", "Portail adhérent"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 39,
    slug: "commerce-local-fidelite",
    categorie: "niche",
    imageId: 39,
    titre: "Commerce Local — Fidélité & Avis",
    descriptionCourte: "Programme fidélité, SMS anniversaire, avis Google auto",
    descriptionLongue: `Pour commerces locaux : programme fidélité automatisé, SMS anniversaire, demande d'avis post-achat.`,
    outils: ["Make", "WhatsApp", "Google Reviews", "Stripe"],
    secteurs: ["retail", "commerce"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 300,
        delaiJours: 3,
        description: "Points fidélité",
        features: ["Points fidélité", "Email anniversaire"],
        workflows: ["Achat → Points fidélité → Email anniversaire"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 700,
        delaiJours: 5,
        description: "Carte fidélité + SMS",
        features: ["Carte fidélité", "SMS anniversaire", "Demande avis"],
        workflows: ["Carte fidélité", "SMS anniversaire", "Demande avis"],
        livrables: ["3 workflows", "Dashboard"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 1400,
        delaiJours: 7,
        description: "Programme complet",
        features: ["Programme complet", "CRM local", "Analytics client"],
        workflows: ["Programme fidélité complet", "CRM", "Analytics"],
        livrables: ["Système complet", "CRM local"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
  {
    id: 40,
    slug: "startup-ops-stack",
    categorie: "niche",
    imageId: 40,
    titre: "Startup — Ops Stack Connecté",
    descriptionCourte: "Notion + Slack + Linear + CRM + email — tout en 1 flux",
    descriptionLongue: `Stack opérationnelle complète pour startup. Connectez Notion, Slack, Linear, CRM, emails — tout automatisé.`,
    outils: ["n8n", "Notion", "Slack", "Linear", "HubSpot"],
    secteurs: ["startup", "tech"],
    prixTiers: [
      {
        nom: "Basique",
        prix: 800,
        delaiJours: 5,
        description: "3 outils connectés",
        features: ["3 outils connectés", "Sync basique"],
        workflows: ["3 outils → Sync basique"],
        livrables: ["Workflow configuré"],
        supportJours: 7,
      },
      {
        nom: "Standard",
        prix: 1800,
        delaiJours: 8,
        description: "5 outils + workflows",
        features: ["5 outils", "Workflows automatisés", "Dashboard ops"],
        workflows: ["5 outils → Workflows auto → Dashboard"],
        livrables: ["3 workflows", "Dashboard ops"],
        supportJours: 14,
        popular: true,
      },
      {
        nom: "Pro",
        prix: 3500,
        delaiJours: 12,
        description: "Stack complet",
        features: ["Stack complet", "Automatisation IA", "Scale ready"],
        workflows: ["Stack complet", "IA automation", "Scale ready"],
        livrables: ["Système complet", "Dashboard", "API"],
        supportJours: 30,
      },
    ],
    workflows: [],
  },
];
